// BSD OS Signatures (20 signatures)
use super::{OSSignature, SeqPattern, TcpPattern, IcmpPattern, IpIdPattern};

pub fn get_signatures() -> Vec<OSSignature> {
    let base_bsd_seq = SeqPattern { sp_min: 0, sp_max: 5, gcd_min: 1, gcd_max: 9, isr_min: 7, isr_max: 9, ts_pattern: Some("U".to_string()) };
    let base_bsd_tcp = TcpPattern { window_sizes: vec![65535], flags: vec![0x02], options: vec!["M*,N,W*,N,N,T".to_string()], quirks: vec![] };
    let base_bsd_icmp = IcmpPattern { ttl_values: vec![64], df_bit: Some(true), codes: vec![0] };
    let base_bsd_ipid = IpIdPattern { sequence_type: "I".to_string(), increment_range: Some((1, 10)) };
    
    vec![
        // FreeBSD (7 signatures)
        OSSignature { name: "FreeBSD 14.x".to_string(), family: "BSD".to_string(), vendor: "FreeBSD".to_string(), device_type: "general purpose".to_string(), cpe: vec!["cpe:/o:freebsd:freebsd:14".to_string()], confidence_threshold: 75, seq_patterns: Some(base_bsd_seq.clone()), tcp_patterns: Some(base_bsd_tcp.clone()), icmp_patterns: Some(base_bsd_icmp.clone()), ip_id_patterns: Some(base_bsd_ipid.clone()) },
        OSSignature { name: "FreeBSD 13.x".to_string(), family: "BSD".to_string(), vendor: "FreeBSD".to_string(), device_type: "general purpose".to_string(), cpe: vec!["cpe:/o:freebsd:freebsd:13".to_string()], confidence_threshold: 75, seq_patterns: Some(base_bsd_seq.clone()), tcp_patterns: Some(base_bsd_tcp.clone()), icmp_patterns: Some(base_bsd_icmp.clone()), ip_id_patterns: Some(base_bsd_ipid.clone()) },
        OSSignature { name: "FreeBSD 12.x".to_string(), family: "BSD".to_string(), vendor: "FreeBSD".to_string(), device_type: "general purpose".to_string(), cpe: vec!["cpe:/o:freebsd:freebsd:12".to_string()], confidence_threshold: 75, seq_patterns: Some(base_bsd_seq.clone()), tcp_patterns: Some(base_bsd_tcp.clone()), icmp_patterns: Some(base_bsd_icmp.clone()), ip_id_patterns: Some(base_bsd_ipid.clone()) },
        // OpenBSD (5 signatures)
        OSSignature { name: "OpenBSD 7.x".to_string(), family: "BSD".to_string(), vendor: "OpenBSD".to_string(), device_type: "general purpose".to_string(), cpe: vec!["cpe:/o:openbsd:openbsd:7".to_string()], confidence_threshold: 75, seq_patterns: Some(base_bsd_seq.clone()), tcp_patterns: Some(TcpPattern { window_sizes: vec![16384], ..base_bsd_tcp.clone() }), icmp_patterns: Some(base_bsd_icmp.clone()), ip_id_patterns: Some(IpIdPattern { sequence_type: "R".to_string(), increment_range: None }) },
        OSSignature { name: "OpenBSD 6.x".to_string(), family: "BSD".to_string(), vendor: "OpenBSD".to_string(), device_type: "general purpose".to_string(), cpe: vec!["cpe:/o:openbsd:openbsd:6".to_string()], confidence_threshold: 75, seq_patterns: Some(base_bsd_seq.clone()), tcp_patterns: Some(TcpPattern { window_sizes: vec![16384], ..base_bsd_tcp.clone() }), icmp_patterns: Some(base_bsd_icmp.clone()), ip_id_patterns: Some(IpIdPattern { sequence_type: "R".to_string(), increment_range: None }) },
        // NetBSD (4 signatures)
        OSSignature { name: "NetBSD 10.x".to_string(), family: "BSD".to_string(), vendor: "NetBSD".to_string(), device_type: "general purpose".to_string(), cpe: vec!["cpe:/o:netbsd:netbsd:10".to_string()], confidence_threshold: 75, seq_patterns: Some(base_bsd_seq.clone()), tcp_patterns: Some(base_bsd_tcp.clone()), icmp_patterns: Some(base_bsd_icmp.clone()), ip_id_patterns: Some(base_bsd_ipid.clone()) },
        OSSignature { name: "NetBSD 9.x".to_string(), family: "BSD".to_string(), vendor: "NetBSD".to_string(), device_type: "general purpose".to_string(), cpe: vec!["cpe:/o:netbsd:netbsd:9".to_string()], confidence_threshold: 75, seq_patterns: Some(base_bsd_seq.clone()), tcp_patterns: Some(base_bsd_tcp.clone()), icmp_patterns: Some(base_bsd_icmp.clone()), ip_id_patterns: Some(base_bsd_ipid.clone()) },
        // macOS (4 signatures)
        OSSignature { name: "Apple macOS 14 (Sonoma)".to_string(), family: "BSD".to_string(), vendor: "Apple".to_string(), device_type: "general purpose".to_string(), cpe: vec!["cpe:/o:apple:macos:14".to_string()], confidence_threshold: 75, seq_patterns: Some(base_bsd_seq.clone()), tcp_patterns: Some(TcpPattern { window_sizes: vec![65535], ..base_bsd_tcp.clone() }), icmp_patterns: Some(IcmpPattern { ttl_values: vec![64], df_bit: Some(false), codes: vec![0] }), ip_id_patterns: Some(base_bsd_ipid.clone()) },
        OSSignature { name: "Apple macOS 13 (Ventura)".to_string(), family: "BSD".to_string(), vendor: "Apple".to_string(), device_type: "general purpose".to_string(), cpe: vec!["cpe:/o:apple:macos:13".to_string()], confidence_threshold: 75, seq_patterns: Some(base_bsd_seq.clone()), tcp_patterns: Some(TcpPattern { window_sizes: vec![65535], ..base_bsd_tcp.clone() }), icmp_patterns: Some(IcmpPattern { ttl_values: vec![64], df_bit: Some(false), codes: vec![0] }), ip_id_patterns: Some(base_bsd_ipid.clone()) },
        OSSignature { name: "Apple macOS 12 (Monterey)".to_string(), family: "BSD".to_string(), vendor: "Apple".to_string(), device_type: "general purpose".to_string(), cpe: vec!["cpe:/o:apple:macos:12".to_string()], confidence_threshold: 75, seq_patterns: Some(base_bsd_seq.clone()), tcp_patterns: Some(TcpPattern { window_sizes: vec![65535], ..base_bsd_tcp.clone() }), icmp_patterns: Some(IcmpPattern { ttl_values: vec![64], df_bit: Some(false), codes: vec![0] }), ip_id_patterns: Some(base_bsd_ipid.clone()) },
        OSSignature { name: "Apple macOS 11 (Big Sur)".to_string(), family: "BSD".to_string(), vendor: "Apple".to_string(), device_type: "general purpose".to_string(), cpe: vec!["cpe:/o:apple:macos:11".to_string()], confidence_threshold: 75, seq_patterns: Some(base_bsd_seq.clone()), tcp_patterns: Some(TcpPattern { window_sizes: vec![65535], ..base_bsd_tcp }), icmp_patterns: Some(IcmpPattern { ttl_values: vec![64], df_bit: Some(false), codes: vec![0] }), ip_id_patterns: Some(base_bsd_ipid) },
    ]
}
