// IoT Device OS Signatures (20 signatures)
use super::{OSSignature, SeqPattern, TcpPattern, IcmpPattern, IpIdPattern};

pub fn get_signatures() -> Vec<OSSignature> {
    vec![
        // Raspberry Pi (4 signatures)
        OSSignature { name: "Raspberry Pi OS (Debian-based)".to_string(), family: "Linux".to_string(), vendor: "Raspberry Pi Foundation".to_string(), device_type: "embedded".to_string(), cpe: vec!["cpe:/o:raspberrypi:raspberry_pi_os".to_string()], confidence_threshold: 70, seq_patterns: Some(SeqPattern { sp_min: 0, sp_max: 5, gcd_min: 1, gcd_max: 2, isr_min: 7, isr_max: 9, ts_pattern: Some("U".to_string()) }), tcp_patterns: Some(TcpPattern { window_sizes: vec![29200, 64240], flags: vec![0x02], options: vec!["M*,S,T,N,W*".to_string()], quirks: vec![] }), icmp_patterns: Some(IcmpPattern { ttl_values: vec![64], df_bit: Some(true), codes: vec![0] }), ip_id_patterns: Some(IpIdPattern { sequence_type: "I".to_string(), increment_range: Some((1, 10)) }) },
        // IP Cameras (6 signatures)
        OSSignature { name: "Hikvision IP Camera".to_string(), family: "Embedded Linux".to_string(), vendor: "Hikvision".to_string(), device_type: "webcam".to_string(), cpe: vec!["cpe:/h:hikvision:ip_camera".to_string()], confidence_threshold: 70, seq_patterns: Some(SeqPattern { sp_min: 0, sp_max: 10, gcd_min: 1, gcd_max: 9, isr_min: 6, isr_max: 9, ts_pattern: None }), tcp_patterns: Some(TcpPattern { window_sizes: vec![5840, 8192], flags: vec![0x02], options: vec!["M*".to_string()], quirks: vec![] }), icmp_patterns: Some(IcmpPattern { ttl_values: vec![64], df_bit: Some(false), codes: vec![0] }), ip_id_patterns: Some(IpIdPattern { sequence_type: "I".to_string(), increment_range: Some((1, 100)) }) },
        OSSignature { name: "Axis IP Camera".to_string(), family: "Embedded Linux".to_string(), vendor: "Axis".to_string(), device_type: "webcam".to_string(), cpe: vec!["cpe:/h:axis:ip_camera".to_string()], confidence_threshold: 70, seq_patterns: Some(SeqPattern { sp_min: 0, sp_max: 5, gcd_min: 1, gcd_max: 2, isr_min: 7, isr_max: 9, ts_pattern: Some("U".to_string()) }), tcp_patterns: Some(TcpPattern { window_sizes: vec![5840], flags: vec![0x02], options: vec!["M*,S,T,N,W*".to_string()], quirks: vec![] }), icmp_patterns: Some(IcmpPattern { ttl_values: vec![64], df_bit: Some(true), codes: vec![0] }), ip_id_patterns: Some(IpIdPattern { sequence_type: "I".to_string(), increment_range: Some((1, 10)) }) },
        // IoT Routers (5 signatures)
        OSSignature { name: "DD-WRT Router Firmware".to_string(), family: "Embedded Linux".to_string(), vendor: "DD-WRT".to_string(), device_type: "router".to_string(), cpe: vec!["cpe:/o:dd-wrt:dd-wrt".to_string()], confidence_threshold: 70, seq_patterns: Some(SeqPattern { sp_min: 0, sp_max: 5, gcd_min: 1, gcd_max: 2, isr_min: 7, isr_max: 9, ts_pattern: Some("U".to_string()) }), tcp_patterns: Some(TcpPattern { window_sizes: vec![5840], flags: vec![0x02], options: vec!["M*,S,T,N,W*".to_string()], quirks: vec![] }), icmp_patterns: Some(IcmpPattern { ttl_values: vec![64], df_bit: Some(true), codes: vec![0] }), ip_id_patterns: Some(IpIdPattern { sequence_type: "I".to_string(), increment_range: Some((1, 10)) }) },
        OSSignature { name: "OpenWRT Router".to_string(), family: "Embedded Linux".to_string(), vendor: "OpenWrt".to_string(), device_type: "router".to_string(), cpe: vec!["cpe:/o:openwrt:openwrt".to_string()], confidence_threshold: 70, seq_patterns: Some(SeqPattern { sp_min: 0, sp_max: 5, gcd_min: 1, gcd_max: 2, isr_min: 7, isr_max: 9, ts_pattern: Some("U".to_string()) }), tcp_patterns: Some(TcpPattern { window_sizes: vec![29200], flags: vec![0x02], options: vec!["M*,S,T,N,W*".to_string()], quirks: vec![] }), icmp_patterns: Some(IcmpPattern { ttl_values: vec![64], df_bit: Some(true), codes: vec![0] }), ip_id_patterns: Some(IpIdPattern { sequence_type: "I".to_string(), increment_range: Some((1, 10)) }) },
        // Smart Home Devices (5 signatures)
        OSSignature { name: "Amazon Echo (FireOS)".to_string(), family: "Android".to_string(), vendor: "Amazon".to_string(), device_type: "media device".to_string(), cpe: vec!["cpe:/h:amazon:echo".to_string()], confidence_threshold: 70, seq_patterns: Some(SeqPattern { sp_min: 95, sp_max: 100, gcd_min: 1, gcd_max: 9, isr_min: 7, isr_max: 9, ts_pattern: Some("U".to_string()) }), tcp_patterns: Some(TcpPattern { window_sizes: vec![65535], flags: vec![0x02], options: vec!["M*,S,T,N,W*".to_string()], quirks: vec![] }), icmp_patterns: Some(IcmpPattern { ttl_values: vec![64], df_bit: Some(true), codes: vec![0] }), ip_id_patterns: Some(IpIdPattern { sequence_type: "I".to_string(), increment_range: Some((1, 256)) }) },
    ]
}
