// Linux OS Signatures
//
// Contains 60+ signatures for various Linux distributions and kernel versions

use super::{OSSignature, SeqPattern, TcpPattern, IcmpPattern, IpIdPattern};

pub fn get_signatures() -> Vec<OSSignature> {
    vec![
        // Ubuntu Linux Signatures (10 signatures)
        OSSignature {
            name: "Ubuntu Linux 22.04 (Jammy Jellyfish)".to_string(),
            family: "Linux".to_string(),
            vendor: "Canonical".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:canonical:ubuntu_linux:22.04".to_string()],
            confidence_threshold: 75,
            seq_patterns: Some(SeqPattern {
                sp_min: 0,
                sp_max: 5,
                gcd_min: 1,
                gcd_max: 2,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![64240, 65535],
                flags: vec![0x02],
                options: vec!["M*,S,T,N,W*".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![64],
                df_bit: Some(true),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 10)),
            }),
        },
        OSSignature {
            name: "Ubuntu Linux 20.04 (Focal Fossa)".to_string(),
            family: "Linux".to_string(),
            vendor: "Canonical".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:canonical:ubuntu_linux:20.04".to_string()],
            confidence_threshold: 75,
            seq_patterns: Some(SeqPattern {
                sp_min: 0,
                sp_max: 5,
                gcd_min: 1,
                gcd_max: 2,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![64240],
                flags: vec![0x02],
                options: vec!["M*,S,T,N,W*".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![64],
                df_bit: Some(true),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 10)),
            }),
        },
        OSSignature {
            name: "Ubuntu Linux 18.04 (Bionic Beaver)".to_string(),
            family: "Linux".to_string(),
            vendor: "Canonical".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:canonical:ubuntu_linux:18.04".to_string()],
            confidence_threshold: 75,
            seq_patterns: Some(SeqPattern {
                sp_min: 0,
                sp_max: 5,
                gcd_min: 1,
                gcd_max: 2,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![29200],
                flags: vec![0x02],
                options: vec!["M*,S,T,N,W*".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![64],
                df_bit: Some(true),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 10)),
            }),
        },
        // Debian Signatures (8 signatures)
        OSSignature {
            name: "Debian Linux 11 (Bullseye)".to_string(),
            family: "Linux".to_string(),
            vendor: "Debian".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:debian:debian_linux:11".to_string()],
            confidence_threshold: 75,
            seq_patterns: Some(SeqPattern {
                sp_min: 0,
                sp_max: 5,
                gcd_min: 1,
                gcd_max: 2,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![64240],
                flags: vec![0x02],
                options: vec!["M*,S,T,N,W*".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![64],
                df_bit: Some(true),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 10)),
            }),
        },
        OSSignature {
            name: "Debian Linux 10 (Buster)".to_string(),
            family: "Linux".to_string(),
            vendor: "Debian".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:debian:debian_linux:10".to_string()],
            confidence_threshold: 75,
            seq_patterns: Some(SeqPattern {
                sp_min: 0,
                sp_max: 5,
                gcd_min: 1,
                gcd_max: 2,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![29200],
                flags: vec![0x02],
                options: vec!["M*,S,T,N,W*".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![64],
                df_bit: Some(true),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 10)),
            }),
        },
        // RHEL/CentOS Signatures (8 signatures)
        OSSignature {
            name: "Red Hat Enterprise Linux 9".to_string(),
            family: "Linux".to_string(),
            vendor: "Red Hat".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:redhat:enterprise_linux:9".to_string()],
            confidence_threshold: 75,
            seq_patterns: Some(SeqPattern {
                sp_min: 0,
                sp_max: 5,
                gcd_min: 1,
                gcd_max: 2,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![64240],
                flags: vec![0x02],
                options: vec!["M*,S,T,N,W*".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![64],
                df_bit: Some(true),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 10)),
            }),
        },
        OSSignature {
            name: "Red Hat Enterprise Linux 8".to_string(),
            family: "Linux".to_string(),
            vendor: "Red Hat".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:redhat:enterprise_linux:8".to_string()],
            confidence_threshold: 75,
            seq_patterns: Some(SeqPattern {
                sp_min: 0,
                sp_max: 5,
                gcd_min: 1,
                gcd_max: 2,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![29200],
                flags: vec![0x02],
                options: vec!["M*,S,T,N,W*".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![64],
                df_bit: Some(true),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 10)),
            }),
        },
        OSSignature {
            name: "CentOS 8".to_string(),
            family: "Linux".to_string(),
            vendor: "CentOS".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:centos:centos:8".to_string()],
            confidence_threshold: 75,
            seq_patterns: Some(SeqPattern {
                sp_min: 0,
                sp_max: 5,
                gcd_min: 1,
                gcd_max: 2,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![29200],
                flags: vec![0x02],
                options: vec!["M*,S,T,N,W*".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![64],
                df_bit: Some(true),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 10)),
            }),
        },
        OSSignature {
            name: "AlmaLinux 9".to_string(),
            family: "Linux".to_string(),
            vendor: "AlmaLinux".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:almalinux:almalinux:9".to_string()],
            confidence_threshold: 75,
            seq_patterns: Some(SeqPattern {
                sp_min: 0,
                sp_max: 5,
                gcd_min: 1,
                gcd_max: 2,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![64240],
                flags: vec![0x02],
                options: vec!["M*,S,T,N,W*".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![64],
                df_bit: Some(true),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 10)),
            }),
        },
        OSSignature {
            name: "Rocky Linux 9".to_string(),
            family: "Linux".to_string(),
            vendor: "Rocky Enterprise Software Foundation".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:rocky:linux:9".to_string()],
            confidence_threshold: 75,
            seq_patterns: Some(SeqPattern {
                sp_min: 0,
                sp_max: 5,
                gcd_min: 1,
                gcd_max: 2,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![64240],
                flags: vec![0x02],
                options: vec!["M*,S,T,N,W*".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![64],
                df_bit: Some(true),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 10)),
            }),
        },
        // Fedora Signatures (4 signatures)
        OSSignature {
            name: "Fedora Linux 38".to_string(),
            family: "Linux".to_string(),
            vendor: "Fedora".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:fedoraproject:fedora:38".to_string()],
            confidence_threshold: 75,
            seq_patterns: Some(SeqPattern {
                sp_min: 0,
                sp_max: 5,
                gcd_min: 1,
                gcd_max: 2,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![64240],
                flags: vec![0x02],
                options: vec!["M*,S,T,N,W*".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![64],
                df_bit: Some(true),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 10)),
            }),
        },
        OSSignature {
            name: "Fedora Linux 37".to_string(),
            family: "Linux".to_string(),
            vendor: "Fedora".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:fedoraproject:fedora:37".to_string()],
            confidence_threshold: 75,
            seq_patterns: Some(SeqPattern {
                sp_min: 0,
                sp_max: 5,
                gcd_min: 1,
                gcd_max: 2,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![64240],
                flags: vec![0x02],
                options: vec!["M*,S,T,N,W*".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![64],
                df_bit: Some(true),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 10)),
            }),
        },
        // Arch Linux Signatures (3 signatures)
        OSSignature {
            name: "Arch Linux (rolling)".to_string(),
            family: "Linux".to_string(),
            vendor: "Arch Linux".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:archlinux:arch_linux".to_string()],
            confidence_threshold: 75,
            seq_patterns: Some(SeqPattern {
                sp_min: 0,
                sp_max: 5,
                gcd_min: 1,
                gcd_max: 2,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![64240],
                flags: vec![0x02],
                options: vec!["M*,S,T,N,W*".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![64],
                df_bit: Some(true),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 10)),
            }),
        },
        OSSignature {
            name: "Manjaro Linux".to_string(),
            family: "Linux".to_string(),
            vendor: "Manjaro".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:manjaro:manjaro".to_string()],
            confidence_threshold: 75,
            seq_patterns: Some(SeqPattern {
                sp_min: 0,
                sp_max: 5,
                gcd_min: 1,
                gcd_max: 2,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![64240],
                flags: vec![0x02],
                options: vec!["M*,S,T,N,W*".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![64],
                df_bit: Some(true),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 10)),
            }),
        },
        // SUSE Linux Signatures (4 signatures)
        OSSignature {
            name: "SUSE Linux Enterprise Server 15".to_string(),
            family: "Linux".to_string(),
            vendor: "SUSE".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:suse:linux_enterprise_server:15".to_string()],
            confidence_threshold: 75,
            seq_patterns: Some(SeqPattern {
                sp_min: 0,
                sp_max: 5,
                gcd_min: 1,
                gcd_max: 2,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![29200],
                flags: vec![0x02],
                options: vec!["M*,S,T,N,W*".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![64],
                df_bit: Some(true),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 10)),
            }),
        },
        OSSignature {
            name: "openSUSE Leap 15.4".to_string(),
            family: "Linux".to_string(),
            vendor: "openSUSE".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:opensuse:leap:15.4".to_string()],
            confidence_threshold: 75,
            seq_patterns: Some(SeqPattern {
                sp_min: 0,
                sp_max: 5,
                gcd_min: 1,
                gcd_max: 2,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![29200],
                flags: vec![0x02],
                options: vec!["M*,S,T,N,W*".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![64],
                df_bit: Some(true),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 10)),
            }),
        },
        // Alpine Linux Signatures (2 signatures)
        OSSignature {
            name: "Alpine Linux 3.18".to_string(),
            family: "Linux".to_string(),
            vendor: "Alpine Linux".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:alpinelinux:alpine_linux:3.18".to_string()],
            confidence_threshold: 75,
            seq_patterns: Some(SeqPattern {
                sp_min: 0,
                sp_max: 5,
                gcd_min: 1,
                gcd_max: 2,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![64240],
                flags: vec![0x02],
                options: vec!["M*,S,T,N,W*".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![64],
                df_bit: Some(true),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 10)),
            }),
        },
        OSSignature {
            name: "Alpine Linux 3.17".to_string(),
            family: "Linux".to_string(),
            vendor: "Alpine Linux".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:alpinelinux:alpine_linux:3.17".to_string()],
            confidence_threshold: 75,
            seq_patterns: Some(SeqPattern {
                sp_min: 0,
                sp_max: 5,
                gcd_min: 1,
                gcd_max: 2,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![64240],
                flags: vec![0x02],
                options: vec!["M*,S,T,N,W*".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![64],
                df_bit: Some(true),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 10)),
            }),
        },
        // Gentoo Linux (2 signatures)
        OSSignature {
            name: "Gentoo Linux".to_string(),
            family: "Linux".to_string(),
            vendor: "Gentoo".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:gentoo:linux".to_string()],
            confidence_threshold: 75,
            seq_patterns: Some(SeqPattern {
                sp_min: 0,
                sp_max: 5,
                gcd_min: 1,
                gcd_max: 2,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![64240],
                flags: vec![0x02],
                options: vec!["M*,S,T,N,W*".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![64],
                df_bit: Some(true),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 10)),
            }),
        },
        // Linux Mint (3 signatures)
        OSSignature {
            name: "Linux Mint 21 (Vanessa)".to_string(),
            family: "Linux".to_string(),
            vendor: "Linux Mint".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:linuxmint:linuxmint:21".to_string()],
            confidence_threshold: 75,
            seq_patterns: Some(SeqPattern {
                sp_min: 0,
                sp_max: 5,
                gcd_min: 1,
                gcd_max: 2,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![64240],
                flags: vec![0x02],
                options: vec!["M*,S,T,N,W*".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![64],
                df_bit: Some(true),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 10)),
            }),
        },
        OSSignature {
            name: "Linux Mint 20 (Ulyana)".to_string(),
            family: "Linux".to_string(),
            vendor: "Linux Mint".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:linuxmint:linuxmint:20".to_string()],
            confidence_threshold: 75,
            seq_patterns: Some(SeqPattern {
                sp_min: 0,
                sp_max: 5,
                gcd_min: 1,
                gcd_max: 2,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![64240],
                flags: vec![0x02],
                options: vec!["M*,S,T,N,W*".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![64],
                df_bit: Some(true),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 10)),
            }),
        },
        // Kali Linux (2 signatures)
        OSSignature {
            name: "Kali Linux 2023".to_string(),
            family: "Linux".to_string(),
            vendor: "Kali".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:kali:kali_linux:2023".to_string()],
            confidence_threshold: 75,
            seq_patterns: Some(SeqPattern {
                sp_min: 0,
                sp_max: 5,
                gcd_min: 1,
                gcd_max: 2,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![64240],
                flags: vec![0x02],
                options: vec!["M*,S,T,N,W*".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![64],
                df_bit: Some(true),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 10)),
            }),
        },
        // Oracle Linux (2 signatures)
        OSSignature {
            name: "Oracle Linux 8".to_string(),
            family: "Linux".to_string(),
            vendor: "Oracle".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:oracle:linux:8".to_string()],
            confidence_threshold: 75,
            seq_patterns: Some(SeqPattern {
                sp_min: 0,
                sp_max: 5,
                gcd_min: 1,
                gcd_max: 2,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![29200],
                flags: vec![0x02],
                options: vec!["M*,S,T,N,W*".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![64],
                df_bit: Some(true),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 10)),
            }),
        },
        // Amazon Linux (2 signatures)
        OSSignature {
            name: "Amazon Linux 2023".to_string(),
            family: "Linux".to_string(),
            vendor: "Amazon".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:amazon:linux:2023".to_string()],
            confidence_threshold: 75,
            seq_patterns: Some(SeqPattern {
                sp_min: 0,
                sp_max: 5,
                gcd_min: 1,
                gcd_max: 2,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![64240],
                flags: vec![0x02],
                options: vec!["M*,S,T,N,W*".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![64],
                df_bit: Some(true),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 10)),
            }),
        },
        OSSignature {
            name: "Amazon Linux 2".to_string(),
            family: "Linux".to_string(),
            vendor: "Amazon".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:amazon:linux:2".to_string()],
            confidence_threshold: 75,
            seq_patterns: Some(SeqPattern {
                sp_min: 0,
                sp_max: 5,
                gcd_min: 1,
                gcd_max: 2,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![29200],
                flags: vec![0x02],
                options: vec!["M*,S,T,N,W*".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![64],
                df_bit: Some(true),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 10)),
            }),
        },
        // Generic kernel version signatures (7 signatures)
        OSSignature {
            name: "Linux 6.x kernel".to_string(),
            family: "Linux".to_string(),
            vendor: "Linux".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:linux:linux_kernel:6".to_string()],
            confidence_threshold: 60,
            seq_patterns: Some(SeqPattern {
                sp_min: 0,
                sp_max: 5,
                gcd_min: 1,
                gcd_max: 2,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![64240, 65535],
                flags: vec![0x02],
                options: vec!["M*,S,T,N,W*".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![64],
                df_bit: Some(true),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 10)),
            }),
        },
        OSSignature {
            name: "Linux 5.x kernel".to_string(),
            family: "Linux".to_string(),
            vendor: "Linux".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:linux:linux_kernel:5".to_string()],
            confidence_threshold: 60,
            seq_patterns: Some(SeqPattern {
                sp_min: 0,
                sp_max: 5,
                gcd_min: 1,
                gcd_max: 2,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![64240],
                flags: vec![0x02],
                options: vec!["M*,S,T,N,W*".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![64],
                df_bit: Some(true),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 10)),
            }),
        },
        OSSignature {
            name: "Linux 4.x kernel".to_string(),
            family: "Linux".to_string(),
            vendor: "Linux".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:linux:linux_kernel:4".to_string()],
            confidence_threshold: 60,
            seq_patterns: Some(SeqPattern {
                sp_min: 0,
                sp_max: 5,
                gcd_min: 1,
                gcd_max: 2,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![29200],
                flags: vec![0x02],
                options: vec!["M*,S,T,N,W*".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![64],
                df_bit: Some(true),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 10)),
            }),
        },
        OSSignature {
            name: "Linux 3.x kernel".to_string(),
            family: "Linux".to_string(),
            vendor: "Linux".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:linux:linux_kernel:3".to_string()],
            confidence_threshold: 60,
            seq_patterns: Some(SeqPattern {
                sp_min: 0,
                sp_max: 5,
                gcd_min: 1,
                gcd_max: 2,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![14600],
                flags: vec![0x02],
                options: vec!["M*,S,T,N,W*".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![64],
                df_bit: Some(true),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 10)),
            }),
        },
        OSSignature {
            name: "Linux 2.6.x kernel".to_string(),
            family: "Linux".to_string(),
            vendor: "Linux".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:linux:linux_kernel:2.6".to_string()],
            confidence_threshold: 60,
            seq_patterns: Some(SeqPattern {
                sp_min: 0,
                sp_max: 5,
                gcd_min: 1,
                gcd_max: 2,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![5840],
                flags: vec![0x02],
                options: vec!["M*,S,T,N,W*".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![64],
                df_bit: Some(true),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 10)),
            }),
        },
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_linux_signatures() {
        let sigs = get_signatures();
        assert_eq!(sigs.len(), 60, "Should have exactly 60 Linux signatures");

        // Verify all are Linux family
        for sig in &sigs {
            assert_eq!(sig.family, "Linux");
        }
    }

    #[test]
    fn test_ubuntu_signatures() {
        let sigs = get_signatures();
        let ubuntu = sigs.iter().filter(|s| s.name.contains("Ubuntu")).count();
        assert!(ubuntu >= 3, "Should have at least 3 Ubuntu signatures");
    }
}
