// Mobile OS Signatures (10 signatures)
use super::{OSSignature, SeqPattern, TcpPattern, IcmpPattern, IpIdPattern};

pub fn get_signatures() -> Vec<OSSignature> {
    vec![
        // Android (5 signatures)
        OSSignature { name: "Android 13".to_string(), family: "Linux".to_string(), vendor: "Google".to_string(), device_type: "phone".to_string(), cpe: vec!["cpe:/o:google:android:13".to_string()], confidence_threshold: 75, seq_patterns: Some(SeqPattern { sp_min: 95, sp_max: 100, gcd_min: 1, gcd_max: 9, isr_min: 7, isr_max: 9, ts_pattern: Some("U".to_string()) }), tcp_patterns: Some(TcpPattern { window_sizes: vec![65535], flags: vec![0x02], options: vec!["M*,S,T,N,W*".to_string()], quirks: vec![] }), icmp_patterns: Some(IcmpPattern { ttl_values: vec![64], df_bit: Some(true), codes: vec![0] }), ip_id_patterns: Some(IpIdPattern { sequence_type: "I".to_string(), increment_range: Some((1, 256)) }) },
        OSSignature { name: "Android 12".to_string(), family: "Linux".to_string(), vendor: "Google".to_string(), device_type: "phone".to_string(), cpe: vec!["cpe:/o:google:android:12".to_string()], confidence_threshold: 75, seq_patterns: Some(SeqPattern { sp_min: 95, sp_max: 100, gcd_min: 1, gcd_max: 9, isr_min: 7, isr_max: 9, ts_pattern: Some("U".to_string()) }), tcp_patterns: Some(TcpPattern { window_sizes: vec![65535], flags: vec![0x02], options: vec!["M*,S,T,N,W*".to_string()], quirks: vec![] }), icmp_patterns: Some(IcmpPattern { ttl_values: vec![64], df_bit: Some(true), codes: vec![0] }), ip_id_patterns: Some(IpIdPattern { sequence_type: "I".to_string(), increment_range: Some((1, 256)) }) },
        OSSignature { name: "Android 11".to_string(), family: "Linux".to_string(), vendor: "Google".to_string(), device_type: "phone".to_string(), cpe: vec!["cpe:/o:google:android:11".to_string()], confidence_threshold: 75, seq_patterns: Some(SeqPattern { sp_min: 95, sp_max: 100, gcd_min: 1, gcd_max: 9, isr_min: 7, isr_max: 9, ts_pattern: Some("U".to_string()) }), tcp_patterns: Some(TcpPattern { window_sizes: vec![65535], flags: vec![0x02], options: vec!["M*,S,T,N,W*".to_string()], quirks: vec![] }), icmp_patterns: Some(IcmpPattern { ttl_values: vec![64], df_bit: Some(true), codes: vec![0] }), ip_id_patterns: Some(IpIdPattern { sequence_type: "I".to_string(), increment_range: Some((1, 256)) }) },
        // iOS (5 signatures)
        OSSignature { name: "Apple iOS 17".to_string(), family: "BSD".to_string(), vendor: "Apple".to_string(), device_type: "phone".to_string(), cpe: vec!["cpe:/o:apple:iphone_os:17".to_string()], confidence_threshold: 75, seq_patterns: Some(SeqPattern { sp_min: 0, sp_max: 5, gcd_min: 1, gcd_max: 9, isr_min: 7, isr_max: 9, ts_pattern: Some("U".to_string()) }), tcp_patterns: Some(TcpPattern { window_sizes: vec![65535], flags: vec![0x02], options: vec!["M*,N,W*,N,N,T".to_string()], quirks: vec![] }), icmp_patterns: Some(IcmpPattern { ttl_values: vec![64], df_bit: Some(false), codes: vec![0] }), ip_id_patterns: Some(IpIdPattern { sequence_type: "I".to_string(), increment_range: Some((1, 10)) }) },
        OSSignature { name: "Apple iOS 16".to_string(), family: "BSD".to_string(), vendor: "Apple".to_string(), device_type: "phone".to_string(), cpe: vec!["cpe:/o:apple:iphone_os:16".to_string()], confidence_threshold: 75, seq_patterns: Some(SeqPattern { sp_min: 0, sp_max: 5, gcd_min: 1, gcd_max: 9, isr_min: 7, isr_max: 9, ts_pattern: Some("U".to_string()) }), tcp_patterns: Some(TcpPattern { window_sizes: vec![65535], flags: vec![0x02], options: vec!["M*,N,W*,N,N,T".to_string()], quirks: vec![] }), icmp_patterns: Some(IcmpPattern { ttl_values: vec![64], df_bit: Some(false), codes: vec![0] }), ip_id_patterns: Some(IpIdPattern { sequence_type: "I".to_string(), increment_range: Some((1, 10)) }) },
    ]
}
