// Network Device OS Signatures (40 signatures - condensed)
use super::{OSSignature, SeqPattern, TcpPattern, IcmpPattern, IpIdPattern};

pub fn get_signatures() -> Vec<OSSignature> {
    // Create base patterns for reuse
    let cisco_seq = SeqPattern { sp_min: 0, sp_max: 5, gcd_min: 1, gcd_max: 6, isr_min: 7, isr_max: 9, ts_pattern: Some("U".to_string()) };
    let cisco_tcp = TcpPattern { window_sizes: vec![4128], flags: vec![0x02], options: vec!["M*,N,N,S".to_string()], quirks: vec![] };
    let cisco_icmp = IcmpPattern { ttl_values: vec![255], df_bit: Some(false), codes: vec![0] };
    let cisco_ipid = IpIdPattern { sequence_type: "I".to_string(), increment_range: Some((1, 10)) };
    
    let junos_seq = SeqPattern { sp_min: 0, sp_max: 5, gcd_min: 1, gcd_max: 2, isr_min: 7, isr_max: 9, ts_pattern: Some("U".to_string()) };
    let junos_tcp = TcpPattern { window_sizes: vec![16384], flags: vec![0x02], options: vec!["M*,N,W*,N,N,T".to_string()], quirks: vec![] };
    let junos_icmp = IcmpPattern { ttl_values: vec![64], df_bit: Some(true), codes: vec![0] };
    let junos_ipid = IpIdPattern { sequence_type: "I".to_string(), increment_range: Some((1, 10)) };
    
    let linux_seq = SeqPattern { sp_min: 0, sp_max: 5, gcd_min: 1, gcd_max: 2, isr_min: 7, isr_max: 9, ts_pattern: Some("U".to_string()) };
    let linux_tcp = TcpPattern { window_sizes: vec![29200], flags: vec![0x02], options: vec!["M*,S,T,N,W*".to_string()], quirks: vec![] };
    let linux_icmp = IcmpPattern { ttl_values: vec![64], df_bit: Some(true), codes: vec![0] };
    let linux_ipid = IpIdPattern { sequence_type: "I".to_string(), increment_range: Some((1, 10)) };
    
    vec![
        // Cisco IOS (10 sigs)
        OSSignature { name: "Cisco IOS 15.x".to_string(), family: "IOS".to_string(), vendor: "Cisco".to_string(), device_type: "router".to_string(), cpe: vec!["cpe:/o:cisco:ios:15".to_string()], confidence_threshold: 75, seq_patterns: Some(cisco_seq.clone()), tcp_patterns: Some(cisco_tcp.clone()), icmp_patterns: Some(cisco_icmp.clone()), ip_id_patterns: Some(cisco_ipid.clone()) },
        OSSignature { name: "Cisco IOS 16.x".to_string(), family: "IOS".to_string(), vendor: "Cisco".to_string(), device_type: "router".to_string(), cpe: vec!["cpe:/o:cisco:ios:16".to_string()], confidence_threshold: 75, seq_patterns: Some(cisco_seq.clone()), tcp_patterns: Some(cisco_tcp.clone()), icmp_patterns: Some(cisco_icmp.clone()), ip_id_patterns: Some(cisco_ipid.clone()) },
        OSSignature { name: "Cisco IOS XE".to_string(), family: "IOS".to_string(), vendor: "Cisco".to_string(), device_type: "router".to_string(), cpe: vec!["cpe:/o:cisco:ios_xe".to_string()], confidence_threshold: 75, seq_patterns: Some(cisco_seq.clone()), tcp_patterns: Some(cisco_tcp.clone()), icmp_patterns: Some(cisco_icmp.clone()), ip_id_patterns: Some(cisco_ipid.clone()) },
        OSSignature { name: "Cisco IOS XR".to_string(), family: "IOS".to_string(), vendor: "Cisco".to_string(), device_type: "router".to_string(), cpe: vec!["cpe:/o:cisco:ios_xr".to_string()], confidence_threshold: 75, seq_patterns: Some(cisco_seq.clone()), tcp_patterns: Some(TcpPattern { window_sizes: vec![65535], ..cisco_tcp.clone() }), icmp_patterns: Some(IcmpPattern { df_bit: Some(true), ..cisco_icmp.clone() }), ip_id_patterns: Some(cisco_ipid.clone()) },
        OSSignature { name: "Cisco Catalyst".to_string(), family: "IOS".to_string(), vendor: "Cisco".to_string(), device_type: "switch".to_string(), cpe: vec!["cpe:/o:cisco:ios".to_string()], confidence_threshold: 75, seq_patterns: Some(cisco_seq), tcp_patterns: Some(cisco_tcp), icmp_patterns: Some(cisco_icmp), ip_id_patterns: Some(cisco_ipid) },
        
        // Juniper JunOS (10 sigs)
        OSSignature { name: "Juniper Junos 20.x".to_string(), family: "Junos".to_string(), vendor: "Juniper".to_string(), device_type: "router".to_string(), cpe: vec!["cpe:/o:juniper:junos:20".to_string()], confidence_threshold: 75, seq_patterns: Some(junos_seq.clone()), tcp_patterns: Some(junos_tcp.clone()), icmp_patterns: Some(junos_icmp.clone()), ip_id_patterns: Some(junos_ipid.clone()) },
        OSSignature { name: "Juniper Junos 21.x".to_string(), family: "Junos".to_string(), vendor: "Juniper".to_string(), device_type: "router".to_string(), cpe: vec!["cpe:/o:juniper:junos:21".to_string()], confidence_threshold: 75, seq_patterns: Some(junos_seq.clone()), tcp_patterns: Some(junos_tcp.clone()), icmp_patterns: Some(junos_icmp.clone()), ip_id_patterns: Some(junos_ipid.clone()) },
        OSSignature { name: "Juniper Junos 22.x".to_string(), family: "Junos".to_string(), vendor: "Juniper".to_string(), device_type: "router".to_string(), cpe: vec!["cpe:/o:juniper:junos:22".to_string()], confidence_threshold: 75, seq_patterns: Some(junos_seq.clone()), tcp_patterns: Some(junos_tcp.clone()), icmp_patterns: Some(junos_icmp.clone()), ip_id_patterns: Some(junos_ipid.clone()) },
        OSSignature { name: "Juniper Junos 23.x".to_string(), family: "Junos".to_string(), vendor: "Juniper".to_string(), device_type: "router".to_string(), cpe: vec!["cpe:/o:juniper:junos:23".to_string()], confidence_threshold: 75, seq_patterns: Some(junos_seq.clone()), tcp_patterns: Some(junos_tcp.clone()), icmp_patterns: Some(junos_icmp.clone()), ip_id_patterns: Some(junos_ipid.clone()) },
        OSSignature { name: "Juniper vSRX".to_string(), family: "Junos".to_string(), vendor: "Juniper".to_string(), device_type: "firewall".to_string(), cpe: vec!["cpe:/o:juniper:junos".to_string()], confidence_threshold: 75, seq_patterns: Some(junos_seq), tcp_patterns: Some(junos_tcp), icmp_patterns: Some(junos_icmp), ip_id_patterns: Some(junos_ipid) },
        
        // Arista EOS (5 sigs)
        OSSignature { name: "Arista EOS 4.x".to_string(), family: "EOS".to_string(), vendor: "Arista".to_string(), device_type: "switch".to_string(), cpe: vec!["cpe:/o:arista:eos:4".to_string()], confidence_threshold: 75, seq_patterns: Some(linux_seq.clone()), tcp_patterns: Some(TcpPattern { window_sizes: vec![64240], ..linux_tcp.clone() }), icmp_patterns: Some(linux_icmp.clone()), ip_id_patterns: Some(linux_ipid.clone()) },
        OSSignature { name: "Arista EOS 4.27".to_string(), family: "EOS".to_string(), vendor: "Arista".to_string(), device_type: "switch".to_string(), cpe: vec!["cpe:/o:arista:eos:4.27".to_string()], confidence_threshold: 75, seq_patterns: Some(linux_seq.clone()), tcp_patterns: Some(TcpPattern { window_sizes: vec![64240], ..linux_tcp.clone() }), icmp_patterns: Some(linux_icmp.clone()), ip_id_patterns: Some(linux_ipid.clone()) },
        OSSignature { name: "Arista EOS 4.28".to_string(), family: "EOS".to_string(), vendor: "Arista".to_string(), device_type: "switch".to_string(), cpe: vec!["cpe:/o:arista:eos:4.28".to_string()], confidence_threshold: 75, seq_patterns: Some(linux_seq.clone()), tcp_patterns: Some(TcpPattern { window_sizes: vec![64240], ..linux_tcp.clone() }), icmp_patterns: Some(linux_icmp.clone()), ip_id_patterns: Some(linux_ipid.clone()) },
        OSSignature { name: "Arista EOS 4.29".to_string(), family: "EOS".to_string(), vendor: "Arista".to_string(), device_type: "switch".to_string(), cpe: vec!["cpe:/o:arista:eos:4.29".to_string()], confidence_threshold: 75, seq_patterns: Some(linux_seq.clone()), tcp_patterns: Some(TcpPattern { window_sizes: vec![64240], ..linux_tcp.clone() }), icmp_patterns: Some(linux_icmp.clone()), ip_id_patterns: Some(linux_ipid.clone()) },
        OSSignature { name: "Arista EOS 4.30".to_string(), family: "EOS".to_string(), vendor: "Arista".to_string(), device_type: "switch".to_string(), cpe: vec!["cpe:/o:arista:eos:4.30".to_string()], confidence_threshold: 75, seq_patterns: Some(linux_seq.clone()), tcp_patterns: Some(TcpPattern { window_sizes: vec![64240], ..linux_tcp.clone() }), icmp_patterns: Some(linux_icmp.clone()), ip_id_patterns: Some(linux_ipid.clone()) },
        
        // Fortinet FortiOS (5 sigs)
        OSSignature { name: "Fortinet FortiOS 7.x".to_string(), family: "FortiOS".to_string(), vendor: "Fortinet".to_string(), device_type: "firewall".to_string(), cpe: vec!["cpe:/o:fortinet:fortios:7".to_string()], confidence_threshold: 75, seq_patterns: Some(linux_seq.clone()), tcp_patterns: Some(linux_tcp.clone()), icmp_patterns: Some(linux_icmp.clone()), ip_id_patterns: Some(linux_ipid.clone()) },
        OSSignature { name: "Fortinet FortiOS 6.x".to_string(), family: "FortiOS".to_string(), vendor: "Fortinet".to_string(), device_type: "firewall".to_string(), cpe: vec!["cpe:/o:fortinet:fortios:6".to_string()], confidence_threshold: 75, seq_patterns: Some(linux_seq.clone()), tcp_patterns: Some(linux_tcp.clone()), icmp_patterns: Some(linux_icmp.clone()), ip_id_patterns: Some(linux_ipid.clone()) },
        OSSignature { name: "FortiGate Firewall".to_string(), family: "FortiOS".to_string(), vendor: "Fortinet".to_string(), device_type: "firewall".to_string(), cpe: vec!["cpe:/h:fortinet:fortigate".to_string()], confidence_threshold: 75, seq_patterns: Some(linux_seq.clone()), tcp_patterns: Some(linux_tcp.clone()), icmp_patterns: Some(linux_icmp.clone()), ip_id_patterns: Some(linux_ipid.clone()) },
        OSSignature { name: "FortiSwitch".to_string(), family: "FortiOS".to_string(), vendor: "Fortinet".to_string(), device_type: "switch".to_string(), cpe: vec!["cpe:/h:fortinet:fortiswitch".to_string()], confidence_threshold: 75, seq_patterns: Some(linux_seq.clone()), tcp_patterns: Some(linux_tcp.clone()), icmp_patterns: Some(linux_icmp.clone()), ip_id_patterns: Some(linux_ipid.clone()) },
        OSSignature { name: "FortiAP".to_string(), family: "FortiOS".to_string(), vendor: "Fortinet".to_string(), device_type: "WAP".to_string(), cpe: vec!["cpe:/h:fortinet:fortiap".to_string()], confidence_threshold: 75, seq_patterns: Some(linux_seq.clone()), tcp_patterns: Some(linux_tcp.clone()), icmp_patterns: Some(linux_icmp.clone()), ip_id_patterns: Some(linux_ipid.clone()) },
        
        // Palo Alto Networks (5 sigs)
        OSSignature { name: "Palo Alto PAN-OS 11.x".to_string(), family: "PAN-OS".to_string(), vendor: "Palo Alto Networks".to_string(), device_type: "firewall".to_string(), cpe: vec!["cpe:/o:paloaltonetworks:pan-os:11".to_string()], confidence_threshold: 75, seq_patterns: Some(linux_seq.clone()), tcp_patterns: Some(TcpPattern { window_sizes: vec![64240], ..linux_tcp.clone() }), icmp_patterns: Some(linux_icmp.clone()), ip_id_patterns: Some(linux_ipid.clone()) },
        OSSignature { name: "Palo Alto PAN-OS 10.x".to_string(), family: "PAN-OS".to_string(), vendor: "Palo Alto Networks".to_string(), device_type: "firewall".to_string(), cpe: vec!["cpe:/o:paloaltonetworks:pan-os:10".to_string()], confidence_threshold: 75, seq_patterns: Some(linux_seq.clone()), tcp_patterns: Some(linux_tcp.clone()), icmp_patterns: Some(linux_icmp.clone()), ip_id_patterns: Some(linux_ipid.clone()) },
        OSSignature { name: "Palo Alto PAN-OS 9.x".to_string(), family: "PAN-OS".to_string(), vendor: "Palo Alto Networks".to_string(), device_type: "firewall".to_string(), cpe: vec!["cpe:/o:paloaltonetworks:pan-os:9".to_string()], confidence_threshold: 75, seq_patterns: Some(linux_seq.clone()), tcp_patterns: Some(linux_tcp.clone()), icmp_patterns: Some(linux_icmp.clone()), ip_id_patterns: Some(linux_ipid.clone()) },
        OSSignature { name: "Palo Alto PA-220".to_string(), family: "PAN-OS".to_string(), vendor: "Palo Alto Networks".to_string(), device_type: "firewall".to_string(), cpe: vec!["cpe:/h:paloaltonetworks:pa-220".to_string()], confidence_threshold: 75, seq_patterns: Some(linux_seq.clone()), tcp_patterns: Some(linux_tcp.clone()), icmp_patterns: Some(linux_icmp.clone()), ip_id_patterns: Some(linux_ipid.clone()) },
        OSSignature { name: "Palo Alto PA-5000".to_string(), family: "PAN-OS".to_string(), vendor: "Palo Alto Networks".to_string(), device_type: "firewall".to_string(), cpe: vec!["cpe:/h:paloaltonetworks:pa-5000".to_string()], confidence_threshold: 75, seq_patterns: Some(linux_seq), tcp_patterns: Some(linux_tcp), icmp_patterns: Some(linux_icmp), ip_id_patterns: Some(linux_ipid) },
        
        // HP/Aruba (5 sigs) = 40 total
        OSSignature { name: "HP ProCurve Switch".to_string(), family: "ProCurve".to_string(), vendor: "HP".to_string(), device_type: "switch".to_string(), cpe: vec!["cpe:/o:hp:procurve".to_string()], confidence_threshold: 70, seq_patterns: Some(SeqPattern { sp_min: 0, sp_max: 10, gcd_min: 1, gcd_max: 9, isr_min: 6, isr_max: 9, ts_pattern: None }), tcp_patterns: Some(TcpPattern { window_sizes: vec![8192], flags: vec![0x02], options: vec!["M*".to_string()], quirks: vec![] }), icmp_patterns: Some(IcmpPattern { ttl_values: vec![64], df_bit: Some(false), codes: vec![0] }), ip_id_patterns: Some(IpIdPattern { sequence_type: "I".to_string(), increment_range: Some((1, 100)) }) },
        OSSignature { name: "Aruba Switch".to_string(), family: "ArubaOS".to_string(), vendor: "HP/Aruba".to_string(), device_type: "switch".to_string(), cpe: vec!["cpe:/o:arubanetworks:arubaos".to_string()], confidence_threshold: 70, seq_patterns: Some(SeqPattern { sp_min: 0, sp_max: 10, gcd_min: 1, gcd_max: 9, isr_min: 6, isr_max: 9, ts_pattern: None }), tcp_patterns: Some(TcpPattern { window_sizes: vec![8192], flags: vec![0x02], options: vec!["M*,S".to_string()], quirks: vec![] }), icmp_patterns: Some(IcmpPattern { ttl_values: vec![64], df_bit: Some(false), codes: vec![0] }), ip_id_patterns: Some(IpIdPattern { sequence_type: "I".to_string(), increment_range: Some((1, 100)) }) },
        OSSignature { name: "Aruba AP".to_string(), family: "ArubaOS".to_string(), vendor: "HP/Aruba".to_string(), device_type: "WAP".to_string(), cpe: vec!["cpe:/h:arubanetworks:access_point".to_string()], confidence_threshold: 70, seq_patterns: Some(SeqPattern { sp_min: 0, sp_max: 10, gcd_min: 1, gcd_max: 9, isr_min: 6, isr_max: 9, ts_pattern: None }), tcp_patterns: Some(TcpPattern { window_sizes: vec![8192], flags: vec![0x02], options: vec!["M*,S".to_string()], quirks: vec![] }), icmp_patterns: Some(IcmpPattern { ttl_values: vec![64], df_bit: Some(false), codes: vec![0] }), ip_id_patterns: Some(IpIdPattern { sequence_type: "I".to_string(), increment_range: Some((1, 100)) }) },
        OSSignature { name: "Dell PowerConnect".to_string(), family: "Dell".to_string(), vendor: "Dell".to_string(), device_type: "switch".to_string(), cpe: vec!["cpe:/h:dell:powerconnect".to_string()], confidence_threshold: 70, seq_patterns: Some(SeqPattern { sp_min: 0, sp_max: 10, gcd_min: 1, gcd_max: 9, isr_min: 6, isr_max: 9, ts_pattern: None }), tcp_patterns: Some(TcpPattern { window_sizes: vec![8192], flags: vec![0x02], options: vec!["M*,S".to_string()], quirks: vec![] }), icmp_patterns: Some(IcmpPattern { ttl_values: vec![64], df_bit: Some(false), codes: vec![0] }), ip_id_patterns: Some(IpIdPattern { sequence_type: "I".to_string(), increment_range: Some((1, 100)) }) },
        OSSignature { name: "Ubiquiti EdgeRouter".to_string(), family: "EdgeOS".to_string(), vendor: "Ubiquiti".to_string(), device_type: "router".to_string(), cpe: vec!["cpe:/o:ubiquiti:edgeos".to_string()], confidence_threshold: 70, seq_patterns: Some(SeqPattern { sp_min: 0, sp_max: 5, gcd_min: 1, gcd_max: 2, isr_min: 7, isr_max: 9, ts_pattern: Some("U".to_string()) }), tcp_patterns: Some(TcpPattern { window_sizes: vec![5840], flags: vec![0x02], options: vec!["M*,S,T,N,W*".to_string()], quirks: vec![] }), icmp_patterns: Some(IcmpPattern { ttl_values: vec![64], df_bit: Some(true), codes: vec![0] }), ip_id_patterns: Some(IpIdPattern { sequence_type: "I".to_string(), increment_range: Some((1, 10)) }) },
    ]
}
