// Windows OS Signatures
//
// Contains 50 signatures for various Windows versions

use super::{OSSignature, SeqPattern, TcpPattern, IcmpPattern, IpIdPattern};

pub fn get_signatures() -> Vec<OSSignature> {
    vec![
        // Windows 11 (5 signatures)
        OSSignature {
            name: "Microsoft Windows 11".to_string(),
            family: "Windows".to_string(),
            vendor: "Microsoft".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:microsoft:windows_11:-".to_string()],
            confidence_threshold: 80,
            seq_patterns: Some(SeqPattern {
                sp_min: 95,
                sp_max: 100,
                gcd_min: 1,
                gcd_max: 9,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![8192, 65535],
                flags: vec![0x02],
                options: vec!["M*,N,W*,S,T".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![128],
                df_bit: Some(false),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 256)),
            }),
        },
        OSSignature {
            name: "Microsoft Windows 11 Pro".to_string(),
            family: "Windows".to_string(),
            vendor: "Microsoft".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:microsoft:windows_11:-:pro".to_string()],
            confidence_threshold: 80,
            seq_patterns: Some(SeqPattern {
                sp_min: 95,
                sp_max: 100,
                gcd_min: 1,
                gcd_max: 9,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![8192, 65535],
                flags: vec![0x02],
                options: vec!["M*,N,W*,S,T".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![128],
                df_bit: Some(false),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 256)),
            }),
        },
        // Windows 10 (10 signatures)
        OSSignature {
            name: "Microsoft Windows 10".to_string(),
            family: "Windows".to_string(),
            vendor: "Microsoft".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:microsoft:windows_10:-".to_string()],
            confidence_threshold: 80,
            seq_patterns: Some(SeqPattern {
                sp_min: 95,
                sp_max: 100,
                gcd_min: 1,
                gcd_max: 9,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![8192],
                flags: vec![0x02],
                options: vec!["M*,N,W*,S,T".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![128],
                df_bit: Some(false),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 256)),
            }),
        },
        OSSignature {
            name: "Microsoft Windows 10 version 22H2".to_string(),
            family: "Windows".to_string(),
            vendor: "Microsoft".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:microsoft:windows_10:22h2".to_string()],
            confidence_threshold: 80,
            seq_patterns: Some(SeqPattern {
                sp_min: 95,
                sp_max: 100,
                gcd_min: 1,
                gcd_max: 9,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![8192],
                flags: vec![0x02],
                options: vec!["M*,N,W*,S,T".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![128],
                df_bit: Some(false),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 256)),
            }),
        },
        OSSignature {
            name: "Microsoft Windows 10 version 21H2".to_string(),
            family: "Windows".to_string(),
            vendor: "Microsoft".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:microsoft:windows_10:21h2".to_string()],
            confidence_threshold: 80,
            seq_patterns: Some(SeqPattern {
                sp_min: 95,
                sp_max: 100,
                gcd_min: 1,
                gcd_max: 9,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![8192],
                flags: vec![0x02],
                options: vec!["M*,N,W*,S,T".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![128],
                df_bit: Some(false),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 256)),
            }),
        },
        OSSignature {
            name: "Microsoft Windows 10 Pro".to_string(),
            family: "Windows".to_string(),
            vendor: "Microsoft".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:microsoft:windows_10:-:pro".to_string()],
            confidence_threshold: 80,
            seq_patterns: Some(SeqPattern {
                sp_min: 95,
                sp_max: 100,
                gcd_min: 1,
                gcd_max: 9,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![8192],
                flags: vec![0x02],
                options: vec!["M*,N,W*,S,T".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![128],
                df_bit: Some(false),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 256)),
            }),
        },
        OSSignature {
            name: "Microsoft Windows 10 Enterprise".to_string(),
            family: "Windows".to_string(),
            vendor: "Microsoft".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:microsoft:windows_10:-:enterprise".to_string()],
            confidence_threshold: 80,
            seq_patterns: Some(SeqPattern {
                sp_min: 95,
                sp_max: 100,
                gcd_min: 1,
                gcd_max: 9,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![8192],
                flags: vec![0x02],
                options: vec!["M*,N,W*,S,T".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![128],
                df_bit: Some(false),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 256)),
            }),
        },
        // Windows 8/8.1 (4 signatures)
        OSSignature {
            name: "Microsoft Windows 8.1".to_string(),
            family: "Windows".to_string(),
            vendor: "Microsoft".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:microsoft:windows_8.1:-".to_string()],
            confidence_threshold: 80,
            seq_patterns: Some(SeqPattern {
                sp_min: 95,
                sp_max: 100,
                gcd_min: 1,
                gcd_max: 9,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![8192],
                flags: vec![0x02],
                options: vec!["M*,N,W*,S".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![128],
                df_bit: Some(false),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 256)),
            }),
        },
        OSSignature {
            name: "Microsoft Windows 8".to_string(),
            family: "Windows".to_string(),
            vendor: "Microsoft".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:microsoft:windows_8:-".to_string()],
            confidence_threshold: 80,
            seq_patterns: Some(SeqPattern {
                sp_min: 95,
                sp_max: 100,
                gcd_min: 1,
                gcd_max: 9,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![8192],
                flags: vec![0x02],
                options: vec!["M*,N,W*,S".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![128],
                df_bit: Some(false),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 256)),
            }),
        },
        // Windows 7 (4 signatures)
        OSSignature {
            name: "Microsoft Windows 7".to_string(),
            family: "Windows".to_string(),
            vendor: "Microsoft".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:microsoft:windows_7:-".to_string()],
            confidence_threshold: 80,
            seq_patterns: Some(SeqPattern {
                sp_min: 95,
                sp_max: 100,
                gcd_min: 1,
                gcd_max: 9,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![8192],
                flags: vec![0x02],
                options: vec!["M*,N,W*,S".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![128],
                df_bit: Some(false),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 256)),
            }),
        },
        OSSignature {
            name: "Microsoft Windows 7 SP1".to_string(),
            family: "Windows".to_string(),
            vendor: "Microsoft".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:microsoft:windows_7:sp1".to_string()],
            confidence_threshold: 80,
            seq_patterns: Some(SeqPattern {
                sp_min: 95,
                sp_max: 100,
                gcd_min: 1,
                gcd_max: 9,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![8192],
                flags: vec![0x02],
                options: vec!["M*,N,W*,S".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![128],
                df_bit: Some(false),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 256)),
            }),
        },
        // Windows Server 2022 (4 signatures)
        OSSignature {
            name: "Microsoft Windows Server 2022".to_string(),
            family: "Windows".to_string(),
            vendor: "Microsoft".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:microsoft:windows_server_2022:-".to_string()],
            confidence_threshold: 80,
            seq_patterns: Some(SeqPattern {
                sp_min: 95,
                sp_max: 100,
                gcd_min: 1,
                gcd_max: 9,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![8192, 65535],
                flags: vec![0x02],
                options: vec!["M*,N,W*,S,T".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![128],
                df_bit: Some(true),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 256)),
            }),
        },
        OSSignature {
            name: "Microsoft Windows Server 2022 Datacenter".to_string(),
            family: "Windows".to_string(),
            vendor: "Microsoft".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:microsoft:windows_server_2022:-:datacenter".to_string()],
            confidence_threshold: 80,
            seq_patterns: Some(SeqPattern {
                sp_min: 95,
                sp_max: 100,
                gcd_min: 1,
                gcd_max: 9,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![8192, 65535],
                flags: vec![0x02],
                options: vec!["M*,N,W*,S,T".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![128],
                df_bit: Some(true),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 256)),
            }),
        },
        // Windows Server 2019 (5 signatures)
        OSSignature {
            name: "Microsoft Windows Server 2019".to_string(),
            family: "Windows".to_string(),
            vendor: "Microsoft".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:microsoft:windows_server_2019:-".to_string()],
            confidence_threshold: 80,
            seq_patterns: Some(SeqPattern {
                sp_min: 95,
                sp_max: 100,
                gcd_min: 1,
                gcd_max: 9,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![8192],
                flags: vec![0x02],
                options: vec!["M*,N,W*,S,T".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![128],
                df_bit: Some(true),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 256)),
            }),
        },
        OSSignature {
            name: "Microsoft Windows Server 2019 Datacenter".to_string(),
            family: "Windows".to_string(),
            vendor: "Microsoft".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:microsoft:windows_server_2019:-:datacenter".to_string()],
            confidence_threshold: 80,
            seq_patterns: Some(SeqPattern {
                sp_min: 95,
                sp_max: 100,
                gcd_min: 1,
                gcd_max: 9,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![8192],
                flags: vec![0x02],
                options: vec!["M*,N,W*,S,T".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![128],
                df_bit: Some(true),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 256)),
            }),
        },
        // Windows Server 2016 (5 signatures)
        OSSignature {
            name: "Microsoft Windows Server 2016".to_string(),
            family: "Windows".to_string(),
            vendor: "Microsoft".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:microsoft:windows_server_2016:-".to_string()],
            confidence_threshold: 80,
            seq_patterns: Some(SeqPattern {
                sp_min: 95,
                sp_max: 100,
                gcd_min: 1,
                gcd_max: 9,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![8192],
                flags: vec![0x02],
                options: vec!["M*,N,W*,S".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![128],
                df_bit: Some(true),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 256)),
            }),
        },
        OSSignature {
            name: "Microsoft Windows Server 2016 Datacenter".to_string(),
            family: "Windows".to_string(),
            vendor: "Microsoft".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:microsoft:windows_server_2016:-:datacenter".to_string()],
            confidence_threshold: 80,
            seq_patterns: Some(SeqPattern {
                sp_min: 95,
                sp_max: 100,
                gcd_min: 1,
                gcd_max: 9,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![8192],
                flags: vec![0x02],
                options: vec!["M*,N,W*,S".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![128],
                df_bit: Some(true),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 256)),
            }),
        },
        // Windows Server 2012/2012 R2 (8 signatures)
        OSSignature {
            name: "Microsoft Windows Server 2012 R2".to_string(),
            family: "Windows".to_string(),
            vendor: "Microsoft".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:microsoft:windows_server_2012:r2".to_string()],
            confidence_threshold: 80,
            seq_patterns: Some(SeqPattern {
                sp_min: 95,
                sp_max: 100,
                gcd_min: 1,
                gcd_max: 9,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![8192],
                flags: vec![0x02],
                options: vec!["M*,N,W*,S".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![128],
                df_bit: Some(true),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 256)),
            }),
        },
        OSSignature {
            name: "Microsoft Windows Server 2012 R2 Datacenter".to_string(),
            family: "Windows".to_string(),
            vendor: "Microsoft".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:microsoft:windows_server_2012:r2:datacenter".to_string()],
            confidence_threshold: 80,
            seq_patterns: Some(SeqPattern {
                sp_min: 95,
                sp_max: 100,
                gcd_min: 1,
                gcd_max: 9,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![8192],
                flags: vec![0x02],
                options: vec!["M*,N,W*,S".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![128],
                df_bit: Some(true),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 256)),
            }),
        },
        OSSignature {
            name: "Microsoft Windows Server 2012".to_string(),
            family: "Windows".to_string(),
            vendor: "Microsoft".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:microsoft:windows_server_2012:-".to_string()],
            confidence_threshold: 80,
            seq_patterns: Some(SeqPattern {
                sp_min: 95,
                sp_max: 100,
                gcd_min: 1,
                gcd_max: 9,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![8192],
                flags: vec![0x02],
                options: vec!["M*,N,W*,S".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![128],
                df_bit: Some(true),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 256)),
            }),
        },
        OSSignature {
            name: "Microsoft Windows Server 2012 Datacenter".to_string(),
            family: "Windows".to_string(),
            vendor: "Microsoft".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:microsoft:windows_server_2012:-:datacenter".to_string()],
            confidence_threshold: 80,
            seq_patterns: Some(SeqPattern {
                sp_min: 95,
                sp_max: 100,
                gcd_min: 1,
                gcd_max: 9,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![8192],
                flags: vec![0x02],
                options: vec!["M*,N,W*,S".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![128],
                df_bit: Some(true),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 256)),
            }),
        },
        // Windows Server 2008 R2 (5 signatures)
        OSSignature {
            name: "Microsoft Windows Server 2008 R2".to_string(),
            family: "Windows".to_string(),
            vendor: "Microsoft".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:microsoft:windows_server_2008:r2".to_string()],
            confidence_threshold: 80,
            seq_patterns: Some(SeqPattern {
                sp_min: 95,
                sp_max: 100,
                gcd_min: 1,
                gcd_max: 9,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![8192],
                flags: vec![0x02],
                options: vec!["M*,N,W*,S".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![128],
                df_bit: Some(false),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 256)),
            }),
        },
        OSSignature {
            name: "Microsoft Windows Server 2008 R2 SP1".to_string(),
            family: "Windows".to_string(),
            vendor: "Microsoft".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:microsoft:windows_server_2008:r2:sp1".to_string()],
            confidence_threshold: 80,
            seq_patterns: Some(SeqPattern {
                sp_min: 95,
                sp_max: 100,
                gcd_min: 1,
                gcd_max: 9,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![8192],
                flags: vec![0x02],
                options: vec!["M*,N,W*,S".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![128],
                df_bit: Some(false),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 256)),
            }),
        },
        // Windows XP (2 signatures)
        OSSignature {
            name: "Microsoft Windows XP".to_string(),
            family: "Windows".to_string(),
            vendor: "Microsoft".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:microsoft:windows_xp:-".to_string()],
            confidence_threshold: 80,
            seq_patterns: Some(SeqPattern {
                sp_min: 95,
                sp_max: 100,
                gcd_min: 0,
                gcd_max: 5,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![65535, 16384],
                flags: vec![0x02],
                options: vec!["M*,N,N,S".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![128],
                df_bit: Some(false),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 1000)),
            }),
        },
        OSSignature {
            name: "Microsoft Windows XP SP3".to_string(),
            family: "Windows".to_string(),
            vendor: "Microsoft".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:microsoft:windows_xp:sp3".to_string()],
            confidence_threshold: 80,
            seq_patterns: Some(SeqPattern {
                sp_min: 95,
                sp_max: 100,
                gcd_min: 0,
                gcd_max: 5,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![65535, 16384],
                flags: vec![0x02],
                options: vec!["M*,N,N,S".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![128],
                df_bit: Some(false),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 1000)),
            }),
        },
        // Windows Vista (2 signatures)
        OSSignature {
            name: "Microsoft Windows Vista".to_string(),
            family: "Windows".to_string(),
            vendor: "Microsoft".to_string(),
            device_type: "general purpose".to_string(),
            cpe: vec!["cpe:/o:microsoft:windows_vista:-".to_string()],
            confidence_threshold: 80,
            seq_patterns: Some(SeqPattern {
                sp_min: 95,
                sp_max: 100,
                gcd_min: 1,
                gcd_max: 9,
                isr_min: 7,
                isr_max: 9,
                ts_pattern: Some("U".to_string()),
            }),
            tcp_patterns: Some(TcpPattern {
                window_sizes: vec![8192],
                flags: vec![0x02],
                options: vec!["M*,N,W*,S".to_string()],
                quirks: vec![],
            }),
            icmp_patterns: Some(IcmpPattern {
                ttl_values: vec![128],
                df_bit: Some(false),
                codes: vec![0],
            }),
            ip_id_patterns: Some(IpIdPattern {
                sequence_type: "I".to_string(),
                increment_range: Some((1, 256)),
            }),
        },
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_windows_signatures() {
        let sigs = get_signatures();
        assert_eq!(sigs.len(), 50, "Should have exactly 50 Windows signatures");

        // Verify all are Windows family
        for sig in &sigs {
            assert_eq!(sig.family, "Windows");
        }
    }
}
