#!/bin/bash
if [ "$1" = "-h" ]
then
  echo "SEARCH THE NMAP SCRIPTING ENGINE DATABASE
by midnightseer

  <arg1> <filter-term>
  # arg 1 - search term
  # arg 2 - optional: an additional filter-term / search parameter"
  exit
fi
filter=$2
function print_divs() {
  a=$1
  for i in $(seq ${#a})
    do
    echo -n "="
  done
}
SAVEIFS=$IFS   # Save current IFS
IFS=$'\n'      # Change IFS to new line
db_output=$(grep $1 /usr/share/nmap/scripts/script.db)
if [[ ! -z $filter ]]
then
  db_output=$(echo "$db_output" | grep $filter) 
fi
db_array=($db_output)
IFS=$SAVEIFS
for line in "${db_array[@]}"
do
  script_name=$(echo "$line" | cut -d " " -f5 | sed 's/,//g' | sed 's/"//g')
  #echo "nmap --script-help=$script_name"
  help_output=$(nmap --script-help=$script_name)
  script_args=$(cat /usr/share/nmap/scripts/$script_name | sed -n '/@args/,/\b/p')
  echo -n "="
  print_divs $script_name
  echo "="
  echo " $script_name "
  echo -n "="
  print_divs $script_name
  echo "="
  echo "$help_output" | sed -e '1,3d'
  echo "Script Arguments:"
  echo "$script_args"
done
