local nmap = require "nmap"
local stdnse = require "stdnse"

description = [[
Associates DCCP & descriptions from a table,
with ports detected as open or filtered by Nmap.
]]

author = "Rubbx"
license = "Same as Nmap--See https://nmap.org/book/man-legal.html"
categories = {"discovery", "safe"}

portrule = function(host, port)
  return true
end

local port_data = {
  {Port = 0, Description = "In programming APIs (not in communication between hosts), requests a system-allocated (dynamic) port"},
  {Port = 1, Description = "TCP Port Service Multiplexer (TCPMUX). Historic. Both TCP and UDP have been assigned to TCPMUX by IANA, but by design only TCP is specified."},
  {Port = 2, Description = "compressnet (Management Utility)"},
  {Port = 3, Description = "compressnet (Compression Process)"},
  {Port = 5, Description = "Remote Job Entry was historically using socket 5 in its old socket form, while MIB PIM has identified it as TCP/5 and IANA has assigned both TCP and UDP 5 to it."},
  {Port = 7, Description = "Echo Protocol"},
  {Port = 9, Description = "Discard Protocol"},
  {Port = 11, Description = "Active Users (systat service)"},
  {Port = 13, Description = "Daytime Protocol"},
  {Port = 15, Description = "Previously netstat service"},
  {Port = 17, Description = "Quote of the Day (QOTD)"},
  {Port = 18, Description = "Message Send Protocol"},
  {Port = 19, Description = "Character Generator Protocol (CHARGEN)"},
  {Port = 20, Description = "File Transfer Protocol (FTP) data transfer"},
  {Port = 21, Description = "File Transfer Protocol (FTP) control (command)"},
  {Port = 22, Description = "Secure Shell (SSH), secure logins, file transfers (scp, sftp) and port forwarding"},
  {Port = 23, Description = "Telnet protocol—unencrypted text communications"},
  {Port = 25, Description = "Simple Mail Transfer Protocol (SMTP), used for email routing between mail servers"},
  {Port = 27, Description = "nsw-fe (NSW User System FE)"},
  {Port = 28, Description = "Palo Alto Networks' Panorama High Availability (HA) sync encrypted port."},
  {Port = 29, Description = "msg-icp (MSG ICP)"},
  {Port = 31, Description = "msg-auth (MSG Authentication)"},
  {Port = 33, Description = "dsp (Display Support Protocol)"},
  {Port = 37, Description = "Time Protocol"},
  {Port = 38, Description = "rap (Route Access Protocol)"},
  {Port = 39, Description = "rlp (Resource Location Protocol)"},
  {Port = 41, Description = "graphics (Graphics)"},
  {Port = 42, Description = "Host Name Server Protocol"},
  {Port = 43, Description = "WHOIS protocol"},
  {Port = 44, Description = "mpm-flags (MPM FLAGS Protocol)"},
  {Port = 45, Description = "mpm (Message Processing Module [recv])"},
  {Port = 46, Description = "mpm-snd (MPM [default send])"},
  {Port = 48, Description = "auditd (Digital Audit Daemon)"},
  {Port = 49, Description = "TACACS Login Host protocol. TACACS+, still in draft which is an improved but distinct version of TACACS, only uses TCP 49."},
  {Port = 50, Description = "re-mail-ck (Remote Mail Checking Protocol)"},
  {Port = 51, Description = "Historically used for Interface Message Processor logical address management, entry has been removed by IANA on 2013-05-25"},
  {Port = 52, Description = "Xerox Network Systems (XNS) Time Protocol. Despite this port being assigned by IANA, the service is meant to work on SPP (ancestor of IPX/SPX), instead of TCP/IP."},
  {Port = 53, Description = "Domain Name System (DNS)"},
  {Port = 54, Description = "Xerox Network Systems (XNS) Clearinghouse (Name Server). Despite this port being assigned by IANA, the service is meant to work on SPP (ancestor of IPX/SPX), instead of TCP/IP."},
  {Port = 55, Description = "isi-gl (ISI Graphics Language)"},
  {Port = 56, Description = "Xerox Network Systems (XNS) Authentication Protocol. Despite this port being assigned by IANA, the service is meant to work on SPP (ancestor of IPX/SPX), instead of TCP/IP."},
  {Port = 58, Description = "Xerox Network Systems (XNS) Mail. Despite this port being assigned by IANA, the service is meant to work on SPP (ancestor of IPX/SPX), instead of TCP/IP."},
  {Port = 61, Description = "Historically assigned to the NIFTP-Based Mail protocol, but was never documented in the related IEN. The port number entry was removed from IANA's registry on 2017-05-18."},
  {Port = 62, Description = "acas (ACA Services)"},
  {Port = 63, Description = "whoispp (whois++)"},
  {Port = 64, Description = "covia (Communications Integrator (CI))"},
  {Port = 65, Description = "tacacs-ds (TACACS-Database Service)"},
  {Port = 66, Description = "sql-net (Oracle SQL*NET)"},
  {Port = 67, Description = "Bootstrap Protocol (BOOTP) server; also used by Dynamic Host Configuration Protocol (DHCP)"},
  {Port = 68, Description = "Bootstrap Protocol (BOOTP) client; also used by Dynamic Host Configuration Protocol (DHCP)"},
  {Port = 69, Description = "Trivial File Transfer Protocol (TFTP)"},
  {Port = 70, Description = "Gopher protocol"},
  {Port = 76, Description = "deos (Distributed External Object Store)"},
  {Port = 78, Description = "vettcp (vettcp)"},
  {Port = 79, Description = "Finger protocol"},
  {Port = 80, Description = "Hypertext Transfer Protocol (HTTP) uses TCP in versions 1.x and 2. HTTP/3 uses QUIC, a transport protocol on top of UDP."},
  {Port = 81, Description = "TorPark onion routing"},
  {Port = 82, Description = "xfer (XFER Utility)"},
  {Port = 82, Description = "TorPark control"},
  {Port = 83, Description = "mit-ml-dev (MIT ML Device)"},
  {Port = 84, Description = "ctf (Common Trace Facility)"},
  {Port = 85, Description = "mit-ml-dev (MIT ML Device)"},
  {Port = 86, Description = "mfcobol (Micro Focus Cobol)"},
  {Port = 88, Description = "Kerberos authentication system"},
  {Port = 89, Description = "su-mit-tg (SU/MIT Telnet Gateway)"},
  {Port = 90, Description = "dnsix (DNSIX Security Attribute Token Map)"},
  {Port = 90, Description = "PointCast (dotcom)"},
  {Port = 91, Description = "mit-dov (MIT Dover Spooler)"},
  {Port = 92, Description = "npp (Network Printing Protocol)"},
  {Port = 93, Description = "dcp (Device Control Protocol)"},
  {Port = 94, Description = "objcall (Tivoli Object Dispatcher)"},
  {Port = 95, Description = "SUPDUP, terminal-independent remote login"},
  {Port = 96, Description = "dixie (DIXIE Protocol Specification)"},
  {Port = 97, Description = "swift-rvf (Swift Remote Virtual File Protocol)"},
  {Port = 98, Description = "tacnews (TAC News)"},
  {Port = 99, Description = "metagram (Metagram Relay)"},
  {Port = 101, Description = "NIC host name"},
  {Port = 102, Description = "ISO Transport Service Access Point (TSAP) Class 0 protocol;"},
  {Port = 104, Description = "Digital Imaging and Communications in Medicine (DICOM; also port 11112)"},
  {Port = 105, Description = "CCSO Nameserver"},
  {Port = 106, Description = "macOS Server, (macOS) password server"},
  {Port = 107, Description = "Remote User Telnet Service (RTelnet)"},
  {Port = 108, Description = "IBM Systems Network Architecture (SNA) gateway access server"},
  {Port = 109, Description = "Post Office Protocol, version 2 (POP2)"},
  {Port = 110, Description = "Post Office Protocol, version 3 (POP3)"},
  {Port = 111, Description = "Open Network Computing Remote Procedure Call (ONC RPC, sometimes referred to as Sun RPC)"},
  {Port = 112, Description = "McIDAS Data Transmission Protocol"},
  {Port = 113, Description = "Ident, authentication service/identification protocol, used by IRC servers to identify users"},
  {Port = 115, Description = "Simple File Transfer Protocol"},
  {Port = 117, Description = "UUCP Mapping Project (path service)"},
  {Port = 118, Description = "Structured Query Language (SQL) Services[jargon]"},
  {Port = 119, Description = "Network News Transfer Protocol (NNTP), retrieval of newsgroup messages"},
  {Port = 123, Description = "Network Time Protocol (NTP), used for time synchronization"},
  {Port = 126, Description = "Formerly Unisys Unitary Login, renamed by Unisys to NXEdit. Used by Unisys Programmer's Workbench for Clearpath MCP, an IDE for Unisys MCP software development"},
  {Port = 135, Description = "DCE endpoint resolution"},
  {Port = 137, Description = "NetBIOS Name Service, used for name registration and resolution"},
  {Port = 138, Description = "NetBIOS Datagram Service"},
  {Port = 139, Description = "NetBIOS Session Service"},
  {Port = 143, Description = "Internet Message Access Protocol (IMAP), management of electronic mail messages on a server"},
  {Port = 151, Description = "HEMS"},
  {Port = 152, Description = "Background File Transfer Program (BFTP)[importance?]"},
  {Port = 153, Description = "Simple Gateway Monitoring Protocol (SGMP), a protocol for remote inspection and alteration of gateway management information"},
  {Port = 156, Description = "Structured Query Language (SQL) Service[jargon]"},
  {Port = 158, Description = "Distributed Mail System Protocol (DMSP, sometimes referred to as Pcmail)[importance?]"},
  {Port = 161, Description = "Simple Network Management Protocol (SNMP)"},
  {Port = 162, Description = "Simple Network Management Protocol Trap (SNMPTRAP)"},
  {Port = 165, Description = "Xerox"},
  {Port = 169, Description = "SEND"},
  {Port = 170, Description = "Network PostScript print server"},
  {Port = 175, Description = "VMNET service using NJE"},
  {Port = 177, Description = "X Display Manager Control Protocol (XDMCP), used for remote logins to an X Display Manager server[self-published source]"},
  {Port = 179, Description = "Border Gateway Protocol (BGP), used to exchange routing and reachability information among autonomous systems (AS) on the Internet"},
  {Port = 180, Description = "ris"},
  {Port = 194, Description = "Internet Relay Chat (IRC)"},
  {Port = 199, Description = "SNMP Unix Multiplexer (SMUX)"},
  {Port = 201, Description = "AppleTalk Routing Maintenance"},
  {Port = 209, Description = "Quick Mail Transfer Protocol[self-published source]"},
  {Port = 210, Description = "ANSI Z39.50"},
  {Port = 213, Description = "Internetwork Packet Exchange (IPX)"},
  {Port = 218, Description = "Message posting protocol (MPP)"},
  {Port = 220, Description = "Internet Message Access Protocol (IMAP), version 3"},
  {Port = 259, Description = "Efficient Short Remote Operations (ESRO)"},
  {Port = 262, Description = "Arcisdms"},
  {Port = 264, Description = "Border Gateway Multicast Protocol (BGMP)"},
  {Port = 280, Description = "http-mgmt"},
  {Port = 300, Description = "ThinLinc Web Access, Spartan protocol "},
  {Port = 308, Description = "Novastor Online Backup"},
  {Port = 311, Description = "macOS Server Admin (officially AppleShare IP Web administration)"},
  {Port = 312, Description = "macOS Xsan administration"},
  {Port = 318, Description = "PKIX Time Stamp Protocol (TSP)"},
  {Port = 319, Description = "Precision Time Protocol (PTP) event messages"},
  {Port = 320, Description = "Precision Time Protocol (PTP) general messages"},
  {Port = 323, Description = "Resource Public Key Infrastructure"},
  {Port = 350, Description = "Mapping of Airline Traffic over Internet Protocol (MATIP) type A"},
  {Port = 351, Description = "MATIP type B"},
  {Port = 356, Description = "cloanto-net-1 (used by Cloanto Amiga Explorer and VMs)"},
  {Port = 366, Description = "On-Demand Mail Relay (ODMR)"},
  {Port = 369, Description = "Rpc2portmap"},
  {Port = 370, Description = "codaauth2, Coda authentication server"},
  {Port = 371, Description = "ClearCase albd"},
  {Port = 376, Description = "Amiga Envoy Network Inquiry Protocol"},
  {Port = 383, Description = "HP data alarm manager"},
  {Port = 384, Description = "A Remote Network Server System"},
  {Port = 387, Description = "AURP (AppleTalk Update-based Routing Protocol)"},
  {Port = 388, Description = "Unidata LDM near real-time data distribution protocol[self-published source][self-published source]"},
  {Port = 389, Description = "Lightweight Directory Access Protocol (LDAP)"},
  {Port = 399, Description = "Digital Equipment Corporation DECnet+ (Phase V) over TCP/IP (RFC1859)"},
  {Port = 401, Description = "Uninterruptible power supply (UPS)"},
  {Port = 427, Description = "Service Location Protocol (SLP)"},
  {Port = 433, Description = "NNTP, part of Network News Transfer Protocol"},
  {Port = 434, Description = "Mobile IP Agent (RFC 5944)"},
  {Port = 443, Description = "Hypertext Transfer Protocol Secure (HTTPS) uses TCP in versions 1.x and 2. HTTP/3 uses QUIC, a transport protocol on top of UDP."},
  {Port = 444, Description = "Simple Network Paging Protocol (SNPP), RFC 1568"},
  {Port = 445, Description = "Microsoft-DS (Directory Services) Active Directory, Windows shares"},
  {Port = 464, Description = "Kpasswd: Kerberos Change/Set password"},
  {Port = 475, Description = "tcpnethaspsrv, Aladdin Knowledge Systems Hasp services"},
  {Port = 491, Description = "GO-Global remote access and application publishing software"},
  {Port = 497, Description = "Retrospect"},
  {Port = 500, Description = "Internet Security Association and Key Management Protocol (ISAKMP) / Internet Key Exchange (IKE)"},
  {Port = 502, Description = "Modbus Protocol"},
  {Port = 504, Description = "Citadel, multiservice protocol for dedicated clients for the Citadel groupware system"},
  {Port = 510, Description = "FirstClass Protocol (FCP), used by FirstClass client/server groupware system"},
  {Port = 512, Description = "Rexec, Remote Process Execution"},
  {Port = 513, Description = "rlogin"},
  {Port = 514, Description = "Remote Shell, used to execute non-interactive commands on a remote system (Remote Shell, rsh, remsh)"},
  {Port = 515, Description = "Line Printer Daemon (LPD), print service"},
  {Port = 517, Description = "Talk"},
  {Port = 518, Description = "NTalk"},
  {Port = 520, Description = "efs, extended file name server"},
  {Port = 521, Description = "Routing Information Protocol Next Generation (RIPng)"},
  {Port = 524, Description = "NetWare Core Protocol (NCP) is used for a variety things such as access to primary NetWare server resources, Time Synchronization, etc."},
  {Port = 525, Description = "Timed, Timeserver"},
  {Port = 530, Description = "Remote procedure call (RPC)"},
  {Port = 532, Description = "netnews"},
  {Port = 533, Description = "netwall, for emergency broadcasts"},
  {Port = 540, Description = "Unix-to-Unix Copy Protocol (UUCP)"},
  {Port = 542, Description = "commerce (Commerce Applications)"},
  {Port = 543, Description = "klogin, Kerberos login"},
  {Port = 544, Description = "kshell, Kerberos Remote shell"},
  {Port = 546, Description = "DHCPv6 client"},
  {Port = 547, Description = "DHCPv6 server"},
  {Port = 548, Description = "Apple Filing Protocol (AFP) over TCP"},
  {Port = 550, Description = "new-rwho, new-who"},
  {Port = 554, Description = "Real Time Streaming Protocol (RTSP)"},
  {Port = 556, Description = "Remotefs, RFS, rfs_server"},
  {Port = 560, Description = "rmonitor, Remote Monitor"},
  {Port = 561, Description = "monitor"},
  {Port = 563, Description = "NNTP over TLS/SSL (NNTPS)"},
  {Port = 564, Description = "9P (Plan 9)"},
  {Port = 585, Description = "Previously assigned for use of Internet Message Access Protocol over TLS/SSL (IMAPS), now deregistered in favour of port 993."},
  {Port = 587, Description = "Email Message Submission (No longer preferred; see port 465.)"},
  {Port = 591, Description = "FileMaker 6.0 (and later) Web Sharing (HTTP Alternate, also see port 80)"},
  {Port = 593, Description = "HTTP RPC Ep Map, Remote procedure call over Hypertext Transfer Protocol, often used by Distributed Component Object Model services and Microsoft Exchange Server"},
  {Port = 601, Description = "Reliable Syslog Service — used for system logging"},
  {Port = 604, Description = "TUNNEL profile, a protocol for BEEP peers to form an application layer tunnel"},
  {Port = 623, Description = "ASF Remote Management and Control Protocol (ASF-RMCP) & IPMI Remote Management Protocol"},
  {Port = 625, Description = "Open Directory Proxy (ODProxy)"},
  {Port = 631, Description = "Internet Printing Protocol (IPP)"},
  {Port = 635, Description = "RLZ DBase"},
  {Port = 636, Description = "Lightweight Directory Access Protocol over TLS/SSL (LDAPS)"},
  {Port = 639, Description = "Multicast Source Discovery Protocol, MSDP"},
  {Port = 641, Description = "SupportSoft Nexus Remote Command (control/listening), a proxy gateway connecting remote control traffic"},
  {Port = 643, Description = "SANity"},
  {Port = 646, Description = "Label Distribution Protocol (LDP), a routing protocol used in MPLS networks"},
  {Port = 647, Description = "DHCP Failover protocol"},
  {Port = 648, Description = "Registry Registrar Protocol (RRP)"},
  {Port = 651, Description = "IEEE-MMS"},
  {Port = 653, Description = "SupportSoft Nexus Remote Command (data), a proxy gateway connecting remote control traffic"},
  {Port = 654, Description = "Media Management System (MMS) Media Management Protocol (MMP)"},
  {Port = 655, Description = "Tinc VPN daemon"},
  {Port = 657, Description = "IBM RMC (Remote monitoring and Control) protocol, used by System p5 AIX Integrated Virtualization Manager (IVM) and Hardware Management Console to connect managed logical partitions (LPAR) to enable dynamic partition reconfiguration"},
  {Port = 660, Description = "macOS Server administration, version 10.4 and earlier"},
  {Port = 666, Description = "Doom, the first online first-person shooter"},
  {Port = 674, Description = "Application Configuration Access Protocol (ACAP)"},
  {Port = 684, Description = "CORBA IIOP SSL"},
  {Port = 688, Description = "REALM-RUSD (ApplianceWare Server Appliance Management Protocol)"},
  {Port = 690, Description = "Velneo Application Transfer Protocol (VATP)"},
  {Port = 691, Description = "MS Exchange Routing"},
  {Port = 694, Description = "Linux-HA high-availability heartbeat"},
  {Port = 695, Description = "IEEE Media Management System over SSL (IEEE-MMS-SSL)"},
  {Port = 698, Description = "Optimized Link State Routing (OLSR)"},
  {Port = 700, Description = "Extensible Provisioning Protocol (EPP), a protocol for communication between domain name registries and registrars (RFC 5734)"},
  {Port = 701, Description = "Link Management Protocol (LMP), a protocol that runs between a pair of nodes and is used to manage traffic engineering (TE) links"},
  {Port = 702, Description = "IRIS (Internet Registry Information Service) over BEEP (Blocks Extensible Exchange Protocol) (RFC 3983)"},
  {Port = 706, Description = "Secure Internet Live Conferencing (SILC)"},
  {Port = 711, Description = "Cisco Tag Distribution Protocol—being replaced by the MPLS Label Distribution Protocol"},
  {Port = 712, Description = "Topology Broadcast based on Reverse-Path Forwarding routing protocol (TBRPF; RFC 3684)"},
  {Port = 749, Description = "Kerberos administration"},
  {Port = 750, Description = "kerberos-iv, Kerberos version IV"},
  {Port = 751, Description = "kerberos_master, Kerberos authentication"},
  {Port = 752, Description = "passwd_server, Kerberos password (kpasswd) server"},
  {Port = 753, Description = "Reverse Routing Header (RRH)"},
  {Port = 754, Description = "tell send"},
  {Port = 760, Description = "krbupdate [kreg], Kerberos registration"},
  {Port = 777, Description = "machine socket eXtension [msx] protocol"},
  {Port = 782, Description = "Conserver serial-console management server"},
  {Port = 783, Description = "SpamAssassin spamd daemon"},
  {Port = 800, Description = "mdbs-daemon"},
  {Port = 802, Description = "MODBUS/TCP Security"},
  {Port = 808, Description = "Microsoft Net.TCP Port Sharing Service"},
  {Port = 829, Description = "Certificate Management Protocol"},
  {Port = 830, Description = "NETCONF over SSH"},
  {Port = 831, Description = "NETCONF over BEEP"},
  {Port = 832, Description = "NETCONF for SOAP over HTTPS"},
  {Port = 833, Description = "NETCONF for SOAP over BEEP"},
  {Port = 843, Description = "Adobe Flash"},
  {Port = 847, Description = "DHCP Failover protocol"},
  {Port = 848, Description = "Group Domain Of Interpretation (GDOI) protocol"},
  {Port = 853, Description = "DNS over TLS (RFC 7858)"},
  {Port = 860, Description = "iSCSI (RFC 3720)"},
  {Port = 861, Description = "OWAMP control (RFC 4656)"},
  {Port = 862, Description = "TWAMP control (RFC 5357)"},
  {Port = 873, Description = "rsync file synchronization protocol"},
  {Port = 888, Description = "cddbp, CD DataBase (CDDB) protocol (CDDBP)"},
  {Port = 897, Description = "Brocade SMI-S RPC"},
  {Port = 898, Description = "Brocade SMI-S RPC SSL"},
  {Port = 902, Description = "VMware ESXi"},
  {Port = 903, Description = "VMware ESXi"},
  {Port = 953, Description = "BIND remote name daemon control (RNDC)"},
  {Port = 981, Description = "Remote HTTPS management for firewall devices running embedded Check Point VPN-1 software"},
  {Port = 987, Description = "Sony PlayStation Wake On Lan"},
  {Port = 988, Description = "Lustre (file system) Protocol (data)."},
  {Port = 989, Description = "FTPS Protocol (data), FTP over TLS/SSL"},
  {Port = 990, Description = "FTPS Protocol (control), FTP over TLS/SSL"},
  {Port = 991, Description = "Netnews Administration System (NAS)"},
  {Port = 992, Description = "Telnet protocol over TLS/SSL"},
  {Port = 993, Description = "Internet Message Access Protocol over TLS/SSL (IMAPS)"},
  {Port = 994, Description = "Previously assigned to Internet Relay Chat over TLS/SSL (IRCS), but was not used in common practice."},
  {Port = 995, Description = "Post Office Protocol 3 over TLS/SSL (POP3S)"},
  {Port = 1010, Description = "ThinLinc web-based administration interface"},
  {Port = 1024, Description = "Reserved"},
  {Port = 1025, Description = "network blackjack"},
  {Port = 1027, Description = "Reserved"},
  {Port = 1029, Description = "Microsoft DCOM services"},
  {Port = 1058, Description = "nim, IBM AIX Network Installation Manager (NIM)"},
  {Port = 1059, Description = "nimreg, IBM AIX Network Installation Manager (NIM)"},
  {Port = 1080, Description = "SOCKS proxy"},
  {Port = 1085, Description = "WebObjects"},
  {Port = 1098, Description = "rmiactivation, Java remote method invocation (RMI) activation"},
  {Port = 1099, Description = "rmiregistry, Java remote method invocation (RMI) registry"},
  {Port = 1100, Description = "SaltoSystems - Handshake for IP-Components"},
  {Port = 1112, Description = "ESET virus updates"},
  {Port = 1113, Description = "Licklider Transmission Protocol (LTP) delay tolerant networking protocol"},
  {Port = 1119, Description = "Battle.net chat/game protocol, used by Blizzard's games"},
  {Port = 1144, Description = "fuscript (Fusion Script) used by Blackmagic Design Fusion and DaVinci Resolve"},
  {Port = 1167, Description = "Cisco IP SLA (Service Assurance Agent)"},
  {Port = 1194, Description = "OpenVPN"},
  {Port = 1198, Description = "The cajo project Free dynamic transparent distributed computing in Java"},
  {Port = 1212, Description = "Equalsocial Fediverse protocol"},
  {Port = 1214, Description = "Kazaa"},
  {Port = 1220, Description = "QuickTime Streaming Server administration"},
  {Port = 1234, Description = "Infoseek search agent"},
  {Port = 1241, Description = "Nessus Security Scanner"},
  {Port = 1270, Description = "Microsoft System Center Operations Manager (SCOM) (formerly Microsoft Operations Manager (MOM)) agent"},
  {Port = 1293, Description = "Internet Protocol Security (IPSec)"},
  {Port = 1311, Description = "Windows RxMon.exe"},
  {Port = 1314, Description = "Festival Speech Synthesis System server"},
  {Port = 1319, Description = "AMX ICSP (Protocol for communications with AMX control systems devices)"},
  {Port = 1337, Description = "Men&Mice DNS"},
  {Port = 1341, Description = "Qubes (Manufacturing Execution System)"},
  {Port = 1344, Description = "Internet Content Adaptation Protocol"},
  {Port = 1352, Description = "HCL Notes / Domino (RPC) protocol"},
  {Port = 1360, Description = "Mimer SQL"},
  {Port = 1414, Description = "IBM WebSphere MQ (formerly known as MQSeries)"},
  {Port = 1417, Description = "Timbuktu Service 1 Port"},
  {Port = 1418, Description = "Timbuktu Service 2 Port"},
  {Port = 1419, Description = "Timbuktu Service 3 Port"},
  {Port = 1420, Description = "Timbuktu Service 4 Port"},
  {Port = 1431, Description = "Reverse Gossip Transport Protocol (RGTP), used to access a General-purpose Reverse-Ordered Gossip Gathering System (GROGGS) bulletin board, such as that implemented on the Cambridge University's Phoenix system"},
  {Port = 1433, Description = "Microsoft SQL Server database management system (MSSQL) server"},
  {Port = 1434, Description = "Microsoft SQL Server database management system (MSSQL) monitor"},
  {Port = 1476, Description = "WiFi Pineapple Hak5."},
  {Port = 1481, Description = "AIRS data interchange."},
  {Port = 1492, Description = "Sid Meier's CivNet, a multiplayer remake of the original Sid Meier's Civilization game[citation needed]"},
  {Port = 1494, Description = "Citrix Independent Computing Architecture (ICA)"},
  {Port = 1500, Description = "IBM Tivoli Storage Manager server"},
  {Port = 1501, Description = "IBM Tivoli Storage Manager client scheduler"},
  {Port = 1503, Description = "Windows Live Messenger (Whiteboard and Application Sharing)"},
  {Port = 1512, Description = "Microsoft's Windows Internet Name Service (WINS)"},
  {Port = 1513, Description = "Garena game client[citation needed]"},
  {Port = 1521, Description = "nCUBE License Manager"},
  {Port = 1524, Description = "ingreslock, ingres"},
  {Port = 1527, Description = "Oracle Net Services, formerly known as SQL*Net"},
  {Port = 1533, Description = "IBM Sametime Virtual Places Chat"},
  {Port = 1534, Description = "Eclipse Target Communication Framework"},
  {Port = 1540, Description = "1C:Enterprise server agent (ragent)"},
  {Port = 1541, Description = "1C:Enterprise master cluster manager (rmngr)"},
  {Port = 1542, Description = "1C:Enterprise configuration repository server"},
  {Port = 1545, Description = "1C:Enterprise cluster administration server (RAS)"},
  {Port = 1547, Description = "Laplink"},
  {Port = 1550, Description = "1C:Enterprise debug server"},
  {Port = 1581, Description = "MIL STD 2045-47001 VMF"},
  {Port = 1583, Description = "Pervasive PSQL"},
  {Port = 1589, Description = "Cisco VLAN Query Protocol (VQP)"},
  {Port = 1604, Description = "DarkComet remote administration tool (RAT)[citation needed]"},
  {Port = 1626, Description = "iSketch"},
  {Port = 1627, Description = "iSketch"},
  {Port = 1628, Description = "LonTalk normal"},
  {Port = 1629, Description = "LonTalk urgent"},
  {Port = 1645, Description = "Early deployment of RADIUS before RFC standardization was done using UDP port number 1645. Enabled for compatibility reasons by default on Cisco[citation needed] and Juniper Networks RADIUS servers. Official port is 1812. TCP port 1645 MUST NOT be used for RADIUS."},
  {Port = 1646, Description = "Old radacct port,[when?] RADIUS accounting protocol. Enabled for compatibility reasons by default on Cisco[citation needed] and Juniper Networks RADIUS servers. Official port is 1813. TCP port 1646 MUST NOT be used for RADIUS."},
  {Port = 1666, Description = "Perforce"},
  {Port = 1677, Description = "Novell GroupWise clients in client/server access mode"},
  {Port = 1688, Description = "Microsoft Key Management Service (KMS) for Windows Activation"},
  {Port = 1701, Description = "Layer 2 Forwarding Protocol (L2F)"},
  {Port = 1707, Description = "Windward Studios games (vdmplay)"},
  {Port = 1716, Description = "America's Army, a massively multiplayer online game (MMO)"},
  {Port = 1719, Description = "H.323 registration and alternate communication"},
  {Port = 1720, Description = "H.323 call signaling"},
  {Port = 1723, Description = "Point-to-Point Tunneling Protocol (PPTP)"},
  {Port = 1755, Description = "Microsoft Media Services (MMS, ms-streaming)"},
  {Port = 1761, Description = "Novell ZENworks"},
  {Port = 1776, Description = "Emergency management information system"},
  {Port = 1801, Description = "Microsoft Message Queuing"},
  {Port = 1812, Description = "RADIUS authentication protocol, radius"},
  {Port = 1813, Description = "RADIUS accounting protocol, radius-acct"},
  {Port = 1863, Description = "Microsoft Notification Protocol (MSNP), used by the Microsoft Messenger service and a number of instant messaging Messenger clients"},
  {Port = 1880, Description = "Node-RED"},
  {Port = 1883, Description = "MQTT (formerly MQ Telemetry Transport)"},
  {Port = 1900, Description = "Simple Service Discovery Protocol (SSDP), discovery of UPnP devices"},
  {Port = 1935, Description = "Macromedia Flash Communications Server MX, the precursor to Adobe Flash Media Server before Macromedia's acquisition by Adobe on December 3, 2005"},
  {Port = 1965, Description = "Gemini, a lightweight, collaboratively designed protocol, striving to fill the gap between Gopher and HTTP"},
  {Port = 1967, Description = "Cisco IOS IP Service Level Agreements (IP SLAs) Control Protocol[citation needed]"},
  {Port = 1972, Description = "InterSystems Caché, and InterSystems IRIS versions 2020.3 and later"},
  {Port = 1984, Description = "Big Brother"},
  {Port = 1985, Description = "Cisco Hot Standby Router Protocol (HSRP)[self-published source]"},
  {Port = 1998, Description = "Cisco X.25 over TCP (XOT) service"},
  {Port = 2000, Description = "Cisco Skinny Client Control Protocol (SCCP)"},
  {Port = 2010, Description = "Artemis: Spaceship Bridge Simulator"},
  {Port = 2033, Description = "Civilization IV multiplayer"},
  {Port = 2049, Description = "Network File System (NFS)"},
  {Port = 2056, Description = "Civilization IV multiplayer"},
  {Port = 2080, Description = "Autodesk NLM (FLEXlm)"},
  {Port = 2082, Description = "cPanel default"},
  {Port = 2083, Description = "Secure RADIUS Service (radsec)"},
  {Port = 2086, Description = "GNUnet"},
  {Port = 2087, Description = "WebHost Manager default TLS"},
  {Port = 2095, Description = "cPanel default web mail"},
  {Port = 2096, Description = "cPanel default TLS web mail"},
  {Port = 2100, Description = "Warzone 2100 multiplayer[citation needed]"},
  {Port = 2101, Description = "Networked Transport of RTCM via Internet Protocol (NTRIP)[citation needed]"},
  {Port = 2102, Description = "Zephyr Notification Service server"},
  {Port = 2103, Description = "Zephyr Notification Service serv-hm connection"},
  {Port = 2104, Description = "Zephyr Notification Service hostmanager"},
  {Port = 2123, Description = "GTP control messages (GTP-C)"},
  {Port = 2142, Description = "TDMoIP (TDM over IP)"},
  {Port = 2152, Description = "GTP user data messages (GTP-U)"},
  {Port = 2159, Description = "GDB remote debug port"},
  {Port = 2181, Description = "EForward-document transport system"},
  {Port = 2195, Description = "Apple Push Notification Service, binary, gateway. Deprecated March 2021."},
  {Port = 2196, Description = "Apple Push Notification Service, binary, feedback. Deprecated March 2021."},
  {Port = 2197, Description = "Apple Push Notification Service, HTTP/2, JSON-based API."},
  {Port = 2210, Description = "NOAAPORT Broadcast Network"},
  {Port = 2211, Description = "EMWIN"},
  {Port = 2221, Description = "ESET anti-virus updates"},
  {Port = 2222, Description = "EtherNet/IP implicit messaging for IO data"},
  {Port = 2240, Description = "General Dynamics Remote Encryptor Configuration Information Protocol (RECIPe)"},
  {Port = 2261, Description = "CoMotion master"},
  {Port = 2262, Description = "CoMotion backup"},
  {Port = 2302, Description = "ArmA multiplayer"},
  {Port = 2303, Description = "ArmA multiplayer (default port for game +1)"},
  {Port = 2305, Description = "ArmA multiplayer (default port for game +3)"},
  {Port = 2351, Description = "AIM game LAN network port[citation needed]"},
  {Port = 2368, Description = "Ghost (blogging platform)"},
  {Port = 2369, Description = "Default for BMC Control-M/Server Configuration Agent"},
  {Port = 2370, Description = "Default for BMC Control-M/Server, to allow the Control-M/Enterprise Manager to connect to the Control-M/Server"},
  {Port = 2372, Description = "Default for K9 Web Protection/parental controls, content filtering agent[citation needed]"},
  {Port = 2375, Description = "Docker REST API (plain)"},
  {Port = 2376, Description = "Docker REST API (SSL)"},
  {Port = 2377, Description = "Docker Swarm cluster management communications[self-published source]"},
  {Port = 2379, Description = "CoreOS etcd client communication"},
  {Port = 2380, Description = "CoreOS etcd server communication"},
  {Port = 2389, Description = "OpenView Session Mgr"},
  {Port = 2399, Description = "FileMaker Data Access Layer (ODBC/JDBC)"},
  {Port = 2401, Description = "CVS version control system password-based server"},
  {Port = 2404, Description = "IEC 60870-5-104, used to send electric power telecontrol messages between two systems via directly connected data circuits"},
  {Port = 2424, Description = "OrientDB database listening for binary client connections"},
  {Port = 2427, Description = "Media Gateway Control Protocol (MGCP) media gateway"},
  {Port = 2447, Description = "ovwdb—OpenView Network Node Manager (NNM) daemon"},
  {Port = 2456, Description = "Valheim"},
  {Port = 2459, Description = "XRPL"},
  {Port = 2480, Description = "OrientDB database listening for HTTP client connections"},
  {Port = 2483, Description = "Oracle database listening for insecure client connections, replaces port 1521[when?]"},
  {Port = 2484, Description = "Oracle database listening for SSL client connections"},
  {Port = 2500, Description = "NetFS communication"},
  {Port = 2501, Description = "NetFS probe"},
  {Port = 2535, Description = "Multicast Address Dynamic Client Allocation Protocol (MADCAP). All standard messages are UDP datagrams."},
  {Port = 2541, Description = "LonTalk/IP"},
  {Port = 2593, Description = "Ultima Online servers[citation needed]"},
  {Port = 2598, Description = "Citrix Independent Computing Architecture (ICA) with Session Reliability; port 1494 without session reliability"},
  {Port = 2599, Description = "Ultima Online servers[citation needed]"},
  {Port = 2628, Description = "DICT"},
  {Port = 2638, Description = "SQL Anywhere database server"},
  {Port = 2710, Description = "XBT Tracker. UDP tracker extension is considered experimental."},
  {Port = 2727, Description = "Media Gateway Control Protocol (MGCP) media gateway controller (call agent)"},
  {Port = 2759, Description = "SuperTuxKart server "},
  {Port = 2761, Description = "DICOM over Integrated Secure Communication Layer (ISCL) "},
  {Port = 2762, Description = "DICOM over TLS"},
  {Port = 2775, Description = "Short Message Peer-to-Peer (SMPP)[citation needed]"},
  {Port = 2809, Description = "corbaloc:iiop URL, per the CORBA 3.0.3 specification"},
  {Port = 2811, Description = "gsi ftp, per the GridFTP specification"},
  {Port = 2827, Description = "I2P BOB Bridge"},
  {Port = 2944, Description = "Megaco text H.248"},
  {Port = 2945, Description = "Megaco binary (ASN.1) H.248"},
  {Port = 2947, Description = "gpsd, GPS daemon"},
  {Port = 2967, Description = "Symantec System Center agent (SSC-AGENT)"},
  {Port = 2989, Description = "Zarkov Intelligent Agent Communication"},
  {Port = 3000, Description = "Ruby on Rails development default"},
  {Port = 3001, Description = "Honeywell Prowatch"},
  {Port = 3004, Description = "iSync"},
  {Port = 3010, Description = "KWS Connector"},
  {Port = 3020, Description = "Common Internet File System (CIFS). See also port 445 for Server Message Block (SMB), a dialect of CIFS."},
  {Port = 3050, Description = "gds-db (Interbase/Firebird databases)"},
  {Port = 3052, Description = "APC PowerChute Network"},
  {Port = 3074, Description = "Xbox LIVE and Games for Windows – Live"},
  {Port = 3101, Description = "BlackBerry Enterprise Server communication protocol"},
  {Port = 3128, Description = "Squid caching web proxy"},
  {Port = 3225, Description = "Fibre Channel over IP (FCIP)"},
  {Port = 3233, Description = "WhiskerControl research control protocol"},
  {Port = 3260, Description = "iSCSI"},
  {Port = 3268, Description = "msft-gc, Microsoft Global Catalog (LDAP service which contains data from Active Directory forests)"},
  {Port = 3269, Description = "msft-gc-ssl, Microsoft Global Catalog over SSL (similar to port 3268, LDAP over SSL)"},
  {Port = 3283, Description = "Net Assistant, a predecessor to Apple Remote Desktop"},
  {Port = 3290, Description = "Virtual Air Traffic Simulation (VATSIM) network voice communication[citation needed]"},
  {Port = 3305, Description = "Odette File Transfer Protocol (OFTP)"},
  {Port = 3306, Description = "MySQL database system"},
  {Port = 3323, Description = "DECE GEODI Server"},
  {Port = 3332, Description = "Thundercloud DataPath Overlay Control"},
  {Port = 3333, Description = "Eggdrop, an IRC bot default port"},
  {Port = 3344, Description = "Repetier-Server"},
  {Port = 3351, Description = "Pervasive PSQL"},
  {Port = 3386, Description = "GTP' 3GPP GSM/UMTS CDR logging protocol"},
  {Port = 3389, Description = "Microsoft Terminal Server (RDP) officially registered as Windows Based Terminal (WBT)"},
  {Port = 3396, Description = "Novell NDPS Printer Agent"},
  {Port = 3412, Description = "xmlBlaster"},
  {Port = 3423, Description = "Xware xTrm Communication Protocol"},
  {Port = 3424, Description = "Xware xTrm Communication Protocol over SSL"},
  {Port = 3435, Description = "Pacom Security User Port"},
  {Port = 3455, Description = "Resource Reservation Protocol (RSVP)"},
  {Port = 3478, Description = "STUN, a protocol for NAT traversal"},
  {Port = 3479, Description = "PlayStation Network"},
  {Port = 3480, Description = "PlayStation Network"},
  {Port = 3483, Description = "Slim Devices discovery protocol"},
  {Port = 3493, Description = "Network UPS Tools (NUT)"},
  {Port = 3503, Description = "MPLS LSP-echo Port"},
  {Port = 3516, Description = "Smartcard Port"},
  {Port = 3527, Description = "Microsoft Message Queuing"},
  {Port = 3535, Description = "SMTP alternate"},
  {Port = 3544, Description = "Teredo tunneling"},
  {Port = 3551, Description = "Apcupsd Information Port "},
  {Port = 3601, Description = "SAP Message Server Port"},
  {Port = 3632, Description = "Distcc, distributed compiler"},
  {Port = 3645, Description = "Cyc"},
  {Port = 3655, Description = "Advanced Systems Concepts, Inc. ActiveBatch Exec Agent"},
  {Port = 3659, Description = "Apple SASL, used by macOS Server Password Server"},
  {Port = 3667, Description = "Information Exchange"},
  {Port = 3671, Description = "KNXnet/IP(EIBnet/IP)"},
  {Port = 3689, Description = "Digital Audio Access Protocol (DAAP), used by Apple's iTunes and AirPlay"},
  {Port = 3690, Description = "Subversion (SVN) version control system"},
  {Port = 3702, Description = "Web Services Dynamic Discovery (WS-Discovery), used by various components of Windows Vista and later"},
  {Port = 3721, Description = "ES File Explorer FTP server"},
  {Port = 3724, Description = "Some Blizzard games"},
  {Port = 3725, Description = "Netia NA-ER Port"},
  {Port = 3749, Description = "CimTrak registered port"},
  {Port = 3768, Description = "RBLcheckd server daemon"},
  {Port = 3784, Description = "Bidirectional Forwarding Detection (BFD)for IPv4 and IPv6 (Single Hop) (RFC 5881)"},
  {Port = 3785, Description = "VoIP program used by Ventrilo"},
  {Port = 3799, Description = "RADIUS change of authorization"},
  {Port = 3804, Description = "Harman Professional HiQnet protocol"},
  {Port = 3825, Description = "RedSeal Networks client/server connection[citation needed]"},
  {Port = 3826, Description = "WarMUX game server"},
  {Port = 3835, Description = "RedSeal Networks client/server connection[citation needed]"},
  {Port = 3830, Description = "System Management Agent, developed and used by Cerner to monitor and manage solutions"},
  {Port = 3856, Description = "ERP Server Application used by F10 Software"},
  {Port = 3880, Description = "IGRS"},
  {Port = 3868, Description = "Diameter base protocol (RFC 3588)"},
  {Port = 3872, Description = "Oracle Enterprise Manager Remote Agent"},
  {Port = 3900, Description = "udt_os, IBM UniData UDT OS"},
  {Port = 3960, Description = "Warframe online interaction[citation needed]"},
  {Port = 3962, Description = "Warframe online interaction[citation needed]"},
  {Port = 3978, Description = "OpenTTD game (masterserver and content service)"},
  {Port = 3978, Description = "Palo Alto Networks' Panorama management of firewalls and log collectors & pre-PAN-OS 8.0 Panorama-to-managed devices software updates."},
  {Port = 3979, Description = "OpenTTD game"},
  {Port = 3999, Description = "Norman distributed scanning service"},
  {Port = 4000, Description = "Diablo II game"},
  {Port = 4001, Description = "Microsoft Ants game"},
  {Port = 4018, Description = "Protocol information and warnings[clarification needed]"},
  {Port = 4035, Description = "IBM Rational Developer for System z Remote System Explorer Daemon"},
  {Port = 4045, Description = "Solaris lockd NFS lock daemon/manager"},
  {Port = 4050, Description = "Mud Master Chat protocol (MMCP) – Peer-to-peer communications between MUD clients."},
  {Port = 4061, Description = "Ice Location Service"},
  {Port = 4069, Description = "Minger Email Address Verification Protocol"},
  {Port = 4070, Description = "Amazon Echo Dot (Amazon Alexa) streaming connection with Spotify"},
  {Port = 4089, Description = "OpenCORE Remote Control Service"},
  {Port = 4090, Description = "Kerio"},
  {Port = 4093, Description = "PxPlus Client server interface ProvideX"},
  {Port = 4096, Description = "Ascom Timeplex Bridge Relay Element (BRE)"},
  {Port = 4105, Description = "Shofar (ShofarNexus)"},
  {Port = 4111, Description = "Xgrid"},
  {Port = 4116, Description = "Smartcard-TLS"},
  {Port = 4123, Description = "Z-Wave Protocol"},
  {Port = 4125, Description = "Microsoft Remote Web Workplace administration"},
  {Port = 4172, Description = "Teradici PCoIP"},
  {Port = 4190, Description = "ManageSieve"},
  {Port = 4197, Description = "Harman International's HControl protocol for control and monitoring of Audio, Video, Lighting and Control equipment"},
  {Port = 4198, Description = "Couch Potato Android app"},
  {Port = 4200, Description = "Angular app"},
  {Port = 4201, Description = "TinyMUD and various derivatives"},
  {Port = 4222, Description = "NATS server default port"},
  {Port = 4226, Description = "Aleph One, a computer game"},
  {Port = 4242, Description = "Orthanc – DICOM server"},
  {Port = 4243, Description = "Docker implementations, redistributions, and setups default[needs update?]"},
  {Port = 4244, Description = "Viber"},
  {Port = 4303, Description = "Simple Railroad Command Protocol (SRCP)"},
  {Port = 4307, Description = "TrueConf Client – TrueConf Server media data exchange"},
  {Port = 4321, Description = "Referral Whois (RWhois) Protocol"},
  {Port = 4433, Description = "SaltoSystems - DTLS Based Communication for NCoder"},
  {Port = 4444, Description = "Oracle WebCenter Content: Content Server—Intradoc Socket port. (formerly known as Oracle Universal Content Management)."},
  {Port = 4455, Description = "OBS Studio built-in WebSocket plugin default port"},
  {Port = 4460, Description = "Network Time Security Key Establishment (NTS)"},
  {Port = 4486, Description = "Integrated Client Message Service (ICMS)"},
  {Port = 4488, Description = "Apple Wide Area Connectivity Service, used by Back to My Mac"},
  {Port = 4500, Description = "IPSec NAT Traversal (RFC 3947, RFC 4306)"},
  {Port = 4534, Description = "Armagetron Advanced server default"},
  {Port = 4560, Description = "default Log4j socketappender port"},
  {Port = 4567, Description = "Sinatra default server port in development mode (HTTP)"},
  {Port = 4569, Description = "Inter-Asterisk eXchange (IAX2)"},
  {Port = 4604, Description = "Identity Registration Protocol"},
  {Port = 4605, Description = "Direct End to End Secure Chat Protocol"},
  {Port = 4662, Description = "OrbitNet Message Service"},
  {Port = 4664, Description = "Google Desktop Search"},
  {Port = 4672, Description = "Default for older versions of eMule"},
  {Port = 4711, Description = "eMule optional web interface"},
  {Port = 4713, Description = "PulseAudio sound server"},
  {Port = 4723, Description = "Appium open source automation tool"},
  {Port = 4724, Description = "Default bootstrap port to use on device to talk to Appium"},
  {Port = 4728, Description = "Computer Associates Desktop and Server Management (DMP)/Port Multiplexer"},
  {Port = 4730, Description = "Gearman's job server"},
  {Port = 4739, Description = "IP Flow Information Export"},
  {Port = 4747, Description = "Apprentice"},
  {Port = 4753, Description = "SIMON (service and discovery)"},
  {Port = 4789, Description = "Virtual eXtensible Local Area Network (VXLAN)"},
  {Port = 4791, Description = "IP Routable RocE (RoCEv2)"},
  {Port = 4840, Description = "OPC UA Connection Protocol (TCP) and OPC UA Multicast Datagram Protocol (UDP) for OPC Unified Architecture from OPC Foundation"},
  {Port = 4843, Description = "OPC UA TCP Protocol over TLS/SSL for OPC Unified Architecture from OPC Foundation"},
  {Port = 4847, Description = "Web Fresh Communication, Quadrion Software & Odorless Entertainment"},
  {Port = 4848, Description = "Java GlassFish Application Server administration default"},
  {Port = 4894, Description = "LysKOM Protocol A"},
  {Port = 4900, Description = "HFSQL (Hyperfile SQL) Mantra Server from PC SOFT"},
  {Port = 4944, Description = "DrayTek DSL Status Monitoring"},
  {Port = 4949, Description = "Munin Resource Monitoring Tool"},
  {Port = 4950, Description = "Cylon Controls UC32 Communications Port"},
  {Port = 5000, Description = "UPnP—Windows network device interoperability"},
  {Port = 5001, Description = "Slingbox and Slingplayer"},
  {Port = 5002, Description = "ASSA ARX access control system"},
  {Port = 5003, Description = "FileMaker – name binding and transport"},
  {Port = 5004, Description = "Real-time Transport Protocol media data (RTP) (RFC 3551, RFC 4571)"},
  {Port = 5005, Description = "Real-time Transport Protocol control protocol (RTCP) (RFC 3551, RFC 4571)"},
  {Port = 5007, Description = "Palo Alto Networks – User-ID agent"},
  {Port = 5010, Description = "Registered to: TelePath (the IBM FlowMark workflow-management system messaging platform) The TCP port is now used for: IBM WebSphere MQ Workflow"},
  {Port = 5011, Description = "TelePath (the IBM FlowMark workflow-management system messaging platform)"},
  {Port = 5022, Description = "MSSQL Server Replication and Database mirroring endpoints"},
  {Port = 5025, Description = "scpi-raw Standard Commands for Programmable Instruments"},
  {Port = 5029, Description = "Sonic Robo Blast 2 and Sonic Robo Blast 2 Kart servers"},
  {Port = 5031, Description = "AVM CAPI-over-TCP (ISDN over Ethernet tunneling)[citation needed]"},
  {Port = 5037, Description = "Android ADB server"},
  {Port = 5044, Description = "Standard port in Filebeats/Logstash implementation of Lumberjack protocol."},
  {Port = 5048, Description = "Texai Message Service"},
  {Port = 5050, Description = "Yahoo! Messenger"},
  {Port = 5051, Description = "ita-agent Symantec Intruder Alert"},
  {Port = 5060, Description = "Session Initiation Protocol (SIP)"},
  {Port = 5061, Description = "Session Initiation Protocol (SIP) over TLS"},
  {Port = 5062, Description = "Localisation access"},
  {Port = 5064, Description = "EPICS Channel Access server"},
  {Port = 5065, Description = "EPICS Channel Access repeater beacon"},
  {Port = 5070, Description = "Binary Floor Control Protocol (BFCP)"},
  {Port = 5075, Description = "EPICS PV Access Data"},
  {Port = 5076, Description = "EPICS PV Access Searches"},
  {Port = 5080, Description = "NEC Phone System SV8100 and SV9100 MLC phones: default iSIP port"},
  {Port = 5084, Description = "EPCglobal Low Level Reader Protocol (LLRP)"},
  {Port = 5085, Description = "EPCglobal Low Level Reader Protocol (LLRP) over TLS"},
  {Port = 5090, Description = "3CX Phone System 3CX Tunnel Protocol, 3CX App API, 3CX Session Border Controller"},
  {Port = 5093, Description = "SafeNet, Inc Sentinel LM, Sentinel RMS, License Manager, client-to-server"},
  {Port = 5099, Description = "SafeNet, Inc Sentinel LM, Sentinel RMS, License Manager, server-to-server"},
  {Port = 5104, Description = "IBM Tivoli Framework NetCOOL/Impact HTTP Service"},
  {Port = 5121, Description = "Neverwinter Nights"},
  {Port = 5150, Description = "ATMP Ascend Tunnel Management Protocol"},
  {Port = 5151, Description = "ESRI SDE Instance"},
  {Port = 5154, Description = "BZFlag"},
  {Port = 5172, Description = "PC over IP Endpoint Management"},
  {Port = 5173, Description = "Vite"},
  {Port = 5190, Description = "AOL Instant Messenger protocol. The chat app is defunct as of 15 December 2017."},
  {Port = 5198, Description = "EchoLink VoIP Amateur Radio Software (Voice)"},
  {Port = 5199, Description = "EchoLink VoIP Amateur Radio Software (Voice)"},
  {Port = 5200, Description = "EchoLink VoIP Amateur Radio Software (Information)"},
  {Port = 5201, Description = "Iperf3 (Tool for measuring TCP and UDP bandwidth performance)"},
  {Port = 5222, Description = "Extensible Messaging and Presence Protocol (XMPP) client connection"},
  {Port = 5223, Description = "Apple Push Notification Service"},
  {Port = 5228, Description = "HP Virtual Room Service"},
  {Port = 5231, Description = "Remote Control of Scan Software for Cruse Scanners"},
  {Port = 5232, Description = "Cruse Scanning System Service"},
  {Port = 5242, Description = "Viber"},
  {Port = 5243, Description = "Viber"},
  {Port = 5246, Description = "Control And Provisioning of Wireless Access Points (CAPWAP) CAPWAP control"},
  {Port = 5247, Description = "Control And Provisioning of Wireless Access Points (CAPWAP) CAPWAP data"},
  {Port = 5269, Description = "Extensible Messaging and Presence Protocol (XMPP) server-to-server connection"},
  {Port = 5280, Description = "Extensible Messaging and Presence Protocol (XMPP)"},
  {Port = 5281, Description = "Extensible Messaging and Presence Protocol (XMPP)"},
  {Port = 5298, Description = "Extensible Messaging and Presence Protocol (XMPP)"},
  {Port = 5310, Description = "Outlaws, a 1997 first-person shooter video game"},
  {Port = 5318, Description = "Certificate Management over CMS"},
  {Port = 5349, Description = "STUN over TLS/DTLS, a protocol for NAT traversal"},
  {Port = 5351, Description = "NAT Port Mapping Protocol and Port Control Protocol—client-requested configuration for connections through network address translators and firewalls"},
  {Port = 5353, Description = "Multicast DNS (mDNS)"},
  {Port = 5355, Description = "Link-Local Multicast Name Resolution (LLMNR), allows hosts to perform name resolution for hosts on the same local link (only provided by Windows Vista and Server 2008)"},
  {Port = 5357, Description = "Web Services for Devices (WSDAPI) (starting from Windows Vista, Windows 7 and Server 2008)"},
  {Port = 5358, Description = "WSDAPI Applications to Use a Secure Channel (only provided by Windows Vista, Windows 7 and Server 2008)"},
  {Port = 5394, Description = "Kega Fusion, a Sega multi-console emulator"},
  {Port = 5402, Description = "Multicast File Transfer Protocol (MFTP)[importance?]"},
  {Port = 5405, Description = "NetSupport Manager"},
  {Port = 5412, Description = "IBM Rational Synergy (Telelogic Synergy) (Continuus CM) Message Router"},
  {Port = 5413, Description = "Wonderware SuiteLink service"},
  {Port = 5417, Description = "SNS Agent"},
  {Port = 5421, Description = "NetSupport Manager"},
  {Port = 5432, Description = "PostgreSQL database system"},
  {Port = 5433, Description = "Bouwsoft file/webserver"},
  {Port = 5445, Description = "Cisco Unified Video Advantage[citation needed]"},
  {Port = 5450, Description = "OSIsoft PI Server Client Access "},
  {Port = 5457, Description = "OSIsoft PI Asset Framework Client Access "},
  {Port = 5458, Description = "OSIsoft PI Notifications Client Access "},
  {Port = 5480, Description = "VMware VAMI (Virtual Appliance Management Infrastructure)—used for initial setup of various administration settings on Virtual Appliances designed using the VAMI architecture."},
  {Port = 5481, Description = "Schneider Electric's ClearSCADA (SCADA implementation for Windows) — used for client-to-server communication."},
  {Port = 5495, Description = "IBM Cognos TM1 Admin server"},
  {Port = 5498, Description = "Hotline tracker server connection"},
  {Port = 5499, Description = "Hotline tracker server discovery"},
  {Port = 5500, Description = "Hotline control connection"},
  {Port = 5501, Description = "Hotline file transfer connection"},
  {Port = 5517, Description = "Setiqueue Proxy server client for SETI@Home project"},
  {Port = 5550, Description = "Hewlett-Packard Data Protector[citation needed]"},
  {Port = 5554, Description = "Fastboot default wireless port"},
  {Port = 5555, Description = "Oracle WebCenter Content: Inbound Refinery—Intradoc Socket port. (formerly known as Oracle Universal Content Management). Port though often changed during installation"},
  {Port = 5556, Description = "Freeciv, Oracle WebLogic Server Node Manager"},
  {Port = 5568, Description = "Session Data Transport (SDT), a part of Architecture for Control Networks (ACN)[full citation needed]"},
  {Port = 5601, Description = "Kibana"},
  {Port = 5631, Description = "pcANYWHEREdata, Symantec pcAnywhere (version 7.52 and later) data"},
  {Port = 5632, Description = "pcANYWHEREstat, Symantec pcAnywhere (version 7.52 and later) status"},
  {Port = 5656, Description = "IBM Lotus Sametime p2p file transfer"},
  {Port = 5666, Description = "NRPE (Nagios)"},
  {Port = 5667, Description = "NSCA (Nagios)"},
  {Port = 5670, Description = "FILEMQ ZeroMQ File Message Queuing Protocol"},
  {Port = 5671, Description = "Advanced Message Queuing Protocol (AMQP) over TLS"},
  {Port = 5672, Description = "Advanced Message Queuing Protocol (AMQP)"},
  {Port = 5678, Description = "n8n"},
  {Port = 5683, Description = "Constrained Application Protocol (CoAP)"},
  {Port = 5684, Description = "Constrained Application Protocol Secure (CoAPs)"},
  {Port = 5693, Description = "Nagios Cross Platform Agent (NCPA)"},
  {Port = 5701, Description = "Hazelcast default communication port"},
  {Port = 5718, Description = "Microsoft DPM Data Channel (with the agent coordinator)"},
  {Port = 5719, Description = "Microsoft DPM Data Channel (with the protection agent)"},
  {Port = 5722, Description = "Microsoft RPC, DFSR (SYSVOL) Replication Service[citation needed]"},
  {Port = 5723, Description = "System Center Operations Manager"},
  {Port = 5724, Description = "Operations Manager Console"},
  {Port = 5741, Description = "IDA Discover Port 1"},
  {Port = 5742, Description = "IDA Discover Port 2"},
  {Port = 5800, Description = "VNC Remote Frame Buffer RFB protocol over HTTP"},
  {Port = 5900, Description = "Remote Frame Buffer protocol (RFB)"},
  {Port = 5905, Description = "Windows service \"C:\\\\Program Files\\\\Intel\\\\Intel(R) Online Connect Access\\\\IntelTechnologyAccessService.exe\" that listens on 127.0.0.1"},
  {Port = 5931, Description = "AMMYY admin Remote Control"},
  {Port = 5938, Description = "TeamViewer remote desktop protocol"},
  {Port = 5984, Description = "CouchDB database server"},
  {Port = 5985, Description = "Windows PowerShell Default psSession Port Windows Remote Management Service (WinRM-HTTP)"},
  {Port = 5986, Description = "Windows PowerShell Default psSession Port Windows Remote Management Service (WinRM-HTTPS)"},
  {Port = 6005, Description = "Default for BMC Software Control-M/Server—Socket used for communication between Control-M processes—though often changed during installation"},
  {Port = 6009, Description = "JD Edwards EnterpriseOne ERP system JDENet messaging client listener"},
  {Port = 6026, Description = "Tigermeeting client/server communication"},
  {Port = 6032, Description = "Tigermeeting API for cloud management - TigerDriver "},
  {Port = 6050, Description = "Arcserve backup"},
  {Port = 6051, Description = "Arcserve backup"},
  {Port = 6081, Description = "Generic Network Virtualization Encapsulation (Geneve)"},
  {Port = 6086, Description = "Peer Distributed Transfer Protocol (PDTP), FTP like file server in a P2P network"},
  {Port = 6100, Description = "Vizrt System"},
  {Port = 6101, Description = "Backup Exec Agent Browser[citation needed]"},
  {Port = 6110, Description = "softcm, HP Softbench CM"},
  {Port = 6111, Description = "spc, HP Softbench Sub-Process Control"},
  {Port = 6112, Description = "dtspcd, execute commands and launch applications remotely"},
  {Port = 6113, Description = "Club Penguin Disney online game for kids, Used by some Blizzard games"},
  {Port = 6136, Description = "ObjectDB database server"},
  {Port = 6159, Description = "ARINC 840 EFB Application Control Interface"},
  {Port = 6160, Description = "Veeam Installer Service"},
  {Port = 6161, Description = "Veeam vPower NFS Service"},
  {Port = 6162, Description = "Veeam Data Mover"},
  {Port = 6163, Description = "Veeam Hyper-V Integration Service"},
  {Port = 6164, Description = "Veeam WAN Accelerator"},
  {Port = 6165, Description = "Veeam WAN Accelerator Data Transfer"},
  {Port = 6167, Description = "Veeam Log Shipping Service"},
  {Port = 6170, Description = "Veeam Mount Server"},
  {Port = 6200, Description = "Oracle WebCenter Content Portable: Content Server (With Native UI) and Inbound Refinery"},
  {Port = 6201, Description = "Thermo-Calc Software AB: Management of service nodes in a processing grid for thermodynamic calculations"},
  {Port = 6225, Description = "Oracle WebCenter Content Portable: Content Server Web UI"},
  {Port = 6227, Description = "Oracle WebCenter Content Portable: JavaDB"},
  {Port = 6240, Description = "Oracle WebCenter Content Portable: Capture"},
  {Port = 6244, Description = "Oracle WebCenter Content Portable: Content Server—Intradoc Socket port"},
  {Port = 6255, Description = "Oracle WebCenter Content Portable: Inbound Refinery—Intradoc Socket port"},
  {Port = 6257, Description = "WinMX (see also 6699)"},
  {Port = 6260, Description = "planet M.U.L.E."},
  {Port = 6262, Description = "Sybase Advantage Database Server"},
  {Port = 6343, Description = "SFlow, sFlow traffic monitoring"},
  {Port = 6346, Description = "gnutella-svc, gnutella (FrostWire, Limewire, Shareaza, etc.)"},
  {Port = 6347, Description = "gnutella-rtr, Gnutella alternate"},
  {Port = 6350, Description = "App Discovery and Access Protocol"},
  {Port = 6379, Description = "Redis key-value data store"},
  {Port = 6389, Description = "EMC CLARiiON"},
  {Port = 6432, Description = "PgBouncer—A connection pooler for PostgreSQL"},
  {Port = 6436, Description = "Leap Motion Websocket Server TLS"},
  {Port = 6437, Description = "Leap Motion Websocket Server"},
  {Port = 6443, Description = "Kubernetes API server "},
  {Port = 6444, Description = "Sun Grid Engine Qmaster Service"},
  {Port = 6445, Description = "Sun Grid Engine Execution Service"},
  {Port = 6454, Description = "Art-Net protocol"},
  {Port = 6464, Description = "Port assignment for medical device communication in accordance to IEEE 11073-20701"},
  {Port = 6513, Description = "NETCONF over TLS"},
  {Port = 6514, Description = "Syslog over TLS"},
  {Port = 6515, Description = "Elipse RPC Protocol (REC)"},
  {Port = 6516, Description = "Windows Admin Center"},
  {Port = 6543, Description = "Pylons project#Pyramid Default Pylons Pyramid web service port"},
  {Port = 6556, Description = "Check MK Agent"},
  {Port = 6566, Description = "SANE (Scanner Access Now Easy)—SANE network scanner daemon"},
  {Port = 6571, Description = "Windows Live FolderShare client"},
  {Port = 6600, Description = "Microsoft Hyper-V Live"},
  {Port = 6601, Description = "Microsoft Forefront Threat Management Gateway"},
  {Port = 6602, Description = "Microsoft Windows WSS Communication"},
  {Port = 6619, Description = "odette-ftps, Odette File Transfer Protocol (OFTP) over TLS/SSL"},
  {Port = 6622, Description = "Multicast FTP"},
  {Port = 6626, Description = "Semaphore Messenger"},
  {Port = 6653, Description = "OpenFlow"},
  {Port = 6679, Description = "Osorno Automation Protocol (OSAUT)"},
  {Port = 6690, Description = "Synology Cloud station"},
  {Port = 6697, Description = "IRC SSL (Secure Internet Relay Chat)—often used"},
  {Port = 6699, Description = "WinMX (see also 6257)"},
  {Port = 6715, Description = "AberMUD and derivatives default port"},
  {Port = 6771, Description = "BitTorrent Local Peer Discovery"},
  {Port = 6801, Description = "ACNET Control System Protocol"},
  {Port = 6888, Description = "MUSE"},
  {Port = 6901, Description = "Windows Live Messenger (Voice)"},
  {Port = 6924, Description = "split-ping, ping with RX/TX latency/loss split"},
  {Port = 6935, Description = "EthoScan Service"},
  {Port = 6936, Description = "XenSource Management Service"},
  {Port = 6969, Description = "acmsoda"},
  {Port = 6980, Description = "Voicemeeter VBAN network audio protocol"},
  {Port = 7000, Description = "Default for Vuze's built-in HTTPS Bittorrent tracker"},
  {Port = 7001, Description = "Avira Server Management Console"},
  {Port = 7002, Description = "Default for BEA WebLogic Server's HTTPS server, though often changed during installation"},
  {Port = 7005, Description = "Default for BMC Software Control-M/Server and Control-M/Agent for Agent-to-Server, though often changed during installation"},
  {Port = 7006, Description = "Default for BMC Software Control-M/Server and Control-M/Agent for Server-to-Agent, though often changed during installation"},
  {Port = 7010, Description = "Default for Cisco AON AMC (AON Management Console)"},
  {Port = 7022, Description = "MSSQL Server Replication and Database mirroring endpoints"},
  {Port = 7023, Description = "Bryan Wilcutt T2-NMCS Protocol for SatCom Modems"},
  {Port = 7025, Description = "Zimbra LMTP [mailbox]—local mail delivery"},
  {Port = 7047, Description = "Zimbra conversion server"},
  {Port = 7070, Description = "Real Time Streaming Protocol (RTSP), used by QuickTime Streaming Server. TCP is used by default, UDP is used as an alternate."},
  {Port = 7077, Description = "Development-Network Authentification-Protocol"},
  {Port = 7133, Description = "Enemy Territory: Quake Wars"},
  {Port = 7144, Description = "Peercast[citation needed]"},
  {Port = 7145, Description = "Peercast[citation needed]"},
  {Port = 7171, Description = "Tibia"},
  {Port = 7262, Description = "CNAP (Calypso Network Access Protocol)"},
  {Port = 7272, Description = "WatchMe – WatchMe Monitoring"},
  {Port = 7306, Description = "Zimbra mysql [mailbox][citation needed]"},
  {Port = 7307, Description = "Zimbra mysql [logger][citation needed]"},
  {Port = 7312, Description = "Sibelius License Server"},
  {Port = 7396, Description = "Web control interface for Folding@home v7.3.6 and later"},
  {Port = 7400, Description = "RTPS (Real Time Publish Subscribe) DDS Discovery"},
  {Port = 7401, Description = "RTPS (Real Time Publish Subscribe) DDS User-Traffic"},
  {Port = 7402, Description = "RTPS (Real Time Publish Subscribe) DDS Meta-Traffic"},
  {Port = 7471, Description = "Stateless Transport Tunneling (STT)"},
  {Port = 7473, Description = "Rise: The Vieneo Province"},
  {Port = 7474, Description = "Neo4J Server webadmin"},
  {Port = 7478, Description = "Default port used by Open iT Server."},
  {Port = 7542, Description = "Saratoga file transfer protocol"},
  {Port = 7547, Description = "CPE WAN Management Protocol (CWMP) Technical Report 069"},
  {Port = 7575, Description = "Populous: The Beginning server"},
  {Port = 7624, Description = "Instrument Neutral Distributed Interface"},
  {Port = 7631, Description = "ERLPhase"},
  {Port = 7634, Description = "hddtemp—Utility to monitor hard drive temperature"},
  {Port = 7655, Description = "I2P SAM Bridge Socket API"},
  {Port = 7659, Description = "Polypheny User Interface (database system)"},
  {Port = 7670, Description = "BrettspielWelt BSW Boardgame Portal"},
  {Port = 7680, Description = "Delivery Optimization for Windows 10"},
  {Port = 7687, Description = "Bolt database connection"},
  {Port = 7717, Description = "Killing Floor"},
  {Port = 7745, Description = "HomeBox"},
  {Port = 7777, Description = "iChat server file transfer proxy"},
  {Port = 7831, Description = "Default used by Smartlaunch Internet Cafe Administration software"},
  {Port = 7880, Description = "PowerSchool Gradebook Server"},
  {Port = 7890, Description = "Default that will be used by the iControl Internet Cafe Suite Administration software"},
  {Port = 7915, Description = "Default for YSFlight server"},
  {Port = 7935, Description = "Fixed port used for Adobe Flash Debug Player to communicate with a debugger (Flash IDE, Flex Builder or fdb)."},
  {Port = 7946, Description = "Docker Swarm communication among nodes"},
  {Port = 7979, Description = "Used by SilverBluff Studios for communication between servers and clients.[citation needed]"},
  {Port = 7990, Description = "Atlassian Bitbucket (default port)[citation needed]"},
  {Port = 8000, Description = "Commonly used for Internet radio streams such as SHOUTcast[citation needed], Icecast and iTunes Radio"},
  {Port = 8005, Description = "Tomcat remote shutdown"},
  {Port = 8006, Description = "Quest AppAssure 5 API"},
  {Port = 8007, Description = "Quest AppAssure 5 Engine"},
  {Port = 8007, Description = "Proxmox Backup Server admin web interface"},
  {Port = 8008, Description = "Alternative port for HTTP. See also ports 80 and 8080."},
  {Port = 8009, Description = "Apache JServ Protocol (ajp13)[citation needed]"},
  {Port = 8010, Description = "Buildbot web status page[citation needed]"},
  {Port = 8042, Description = "Orthanc – REST API over HTTP"},
  {Port = 8061, Description = "Nikatron Device Protocol (nikatron-dev)"},
  {Port = 8069, Description = "OpenERP 5.0 XML-RPC protocol"},
  {Port = 8070, Description = "OpenERP 5.0 NET-RPC protocol"},
  {Port = 8074, Description = "Gadu-Gadu"},
  {Port = 8075, Description = "Killing Floor web administration interface[citation needed]"},
  {Port = 8080, Description = "Alternative port for HTTP. See also ports 80 and 8008."},
  {Port = 8081, Description = "Sun Proxy Admin Service"},
  {Port = 8088, Description = "Asterisk management access via HTTP[citation needed]"},
  {Port = 8089, Description = "Splunk daemon management"},
  {Port = 8090, Description = "Atlassian Confluence"},
  {Port = 8091, Description = "CouchBase web administration"},
  {Port = 8092, Description = "CouchBase API"},
  {Port = 8096, Description = "Emby and Jellyfin HTTP port"},
  {Port = 8100, Description = "SaltoSystems - Pro Access Space Service"},
  {Port = 8102, Description = "SaltoSystems - Used for LocalIO-Bridge for USB-Devices"},
  {Port = 8111, Description = "JOSM Remote Control"},
  {Port = 8112, Description = "PAC Pacifica Coin"},
  {Port = 8116, Description = "Check Point Cluster Control Protocol"},
  {Port = 8118, Description = "Privoxy—advertisement-filtering Web proxy"},
  {Port = 8123, Description = "Polipo Web proxy"},
  {Port = 8125, Description = "StatsD server"},
  {Port = 8139, Description = "Puppet (software) Client agent"},
  {Port = 8140, Description = "Puppet (software) Master server"},
  {Port = 8172, Description = "Microsoft Remote Administration for IIS Manager"},
  {Port = 8184, Description = "NCSA Brown Dog Data Access Proxy"},
  {Port = 8188, Description = "ComfyUI Web Interface"},
  {Port = 8200, Description = "GoToMyPC"},
  {Port = 8222, Description = "VMware VI Web Access via HTTP"},
  {Port = 8236, Description = "jRCS listener for Rocket Software jBASE Remote Connectivity Server"},
  {Port = 8243, Description = "HTTPS listener for Apache Synapse"},
  {Port = 8245, Description = "Dynamic DNS for at least No-IP and DynDNS"},
  {Port = 8280, Description = "HTTP listener for Apache Synapse"},
  {Port = 8281, Description = "HTTP Listener for Gatecraft Plugin"},
  {Port = 8291, Description = "Winbox—Default on a MikroTik RouterOS for a Windows application used to administer MikroTik RouterOS"},
  {Port = 8303, Description = "Teeworlds Server"},
  {Port = 8332, Description = "Bitcoin JSON-RPC server"},
  {Port = 8333, Description = "Bitcoin"},
  {Port = 8334, Description = "Filestash server (default) "},
  {Port = 8337, Description = "VisualSVN Distributed File System Service (VDFS)"},
  {Port = 8384, Description = "Syncthing web GUI"},
  {Port = 8388, Description = "Shadowsocks proxy server[citation needed]"},
  {Port = 8400, Description = "Commvault Communications Service (GxCVD, found in all client computers)"},
  {Port = 8401, Description = "Commvault Server Event Manager (GxEvMgrS, available in CommServe)"},
  {Port = 8403, Description = "Commvault Firewall (GxFWD, tunnel port for HTTP/HTTPS)"},
  {Port = 8443, Description = "SW Soft Plesk Control Panel"},
  {Port = 8444, Description = "Bitmessage"},
  {Port = 8448, Description = "Matrix homeserver federation over HTTPS"},
  {Port = 8484, Description = "MapleStory Login Server"},
  {Port = 8500, Description = "Adobe ColdFusion built-in web server"},
  {Port = 8501, Description = "Streamlit Open-source Python framework for machine learning and data science"},
  {Port = 8530, Description = "Windows Server Update Services over HTTP, when using the default role installation settings in Windows Server 2012 and later versions."},
  {Port = 8531, Description = "Windows Server Update Services over HTTPS, when using the default role installation settings in Windows Server 2012 and later versions."},
  {Port = 8555, Description = "Symantec DLP OCR Engine "},
  {Port = 8580, Description = "Freegate, an Internet anonymizer and proxy tool"},
  {Port = 8601, Description = "Wavestore VMS protocol "},
  {Port = 8629, Description = "Tibero database[citation needed]"},
  {Port = 8642, Description = "Lotus Notes Traveler auto synchronization for Windows Mobile and Nokia devices"},
  {Port = 8691, Description = "Ultra Fractal, a fractal generation and rendering software application – distributed calculations over networked computers"},
  {Port = 8765, Description = "Default port of a local GUN relay peer that the Internet Archive and others use as a decentralized mirror for censorship resistance."},
  {Port = 8767, Description = "Voice channel of TeamSpeak 2, a proprietary Voice over IP protocol targeted at gamers[citation needed]"},
  {Port = 8834, Description = "Nessus, a vulnerability scanner – remote XML-RPC web server[independent source needed]"},
  {Port = 8840, Description = "Opera Unite, an extensible framework for web applications"},
  {Port = 8880, Description = "Alternate port of CDDB (Compact Disc Database) protocol, used to look up audio CD (compact disc) information over the Internet. See also port 888."},
  {Port = 8883, Description = "Secure MQTT (MQTT over TLS)"},
  {Port = 8887, Description = "HyperVM over HTTP[citation needed]"},
  {Port = 8888, Description = "HyperVM over HTTPS[citation needed]"},
  {Port = 8889, Description = "MAMP"},
  {Port = 8920, Description = "Jellyfin HTTPS port"},
  {Port = 8983, Description = "Apache Solr"},
  {Port = 8997, Description = "Alternate port for I2P Monotone Proxy[jargon]"},
  {Port = 8998, Description = "I2P Monotone Proxy[jargon]"},
  {Port = 8999, Description = "Alternate port for I2P Monotone Proxy[jargon]"},
  {Port = 9000, Description = "SonarQube Web Server"},
  {Port = 9001, Description = "ETL Service Manager"},
  {Port = 9002, Description = "Newforma Server comms"},
  {Port = 9003, Description = "Xdebug default client port"},
  {Port = 9006, Description = "Tomcat in standalone mode"},
  {Port = 9008, Description = "Zerto VRA encrypted communications listener"},
  {Port = 9030, Description = "Tor network default (DirPort)"},
  {Port = 9042, Description = "Apache Cassandra native protocol clients"},
  {Port = 9043, Description = "WebSphere Application Server Administration Console secure"},
  {Port = 9060, Description = "WebSphere Application Server Administration Console"},
  {Port = 9080, Description = "glrpc, Groove Collaboration software GLRPC"},
  {Port = 9081, Description = "Zerto ZVM to ZVM communication"},
  {Port = 9090, Description = "Cockpit"},
  {Port = 9091, Description = "Openfire Administration console (SSL secured)"},
  {Port = 9092, Description = "H2 (DBMS) Database server"},
  {Port = 9095, Description = "Networker Web user interface server"},
  {Port = 9100, Description = "PDL Data Stream, used for printing to certain network printers"},
  {Port = 9101, Description = "Bacula Director"},
  {Port = 9102, Description = "Bacula File Daemon"},
  {Port = 9103, Description = "Bacula Storage Daemon"},
  {Port = 9116, Description = "SNMP-exporter (Prometheus)"},
  {Port = 9119, Description = "MXit Instant Messenger"},
  {Port = 9150, Description = "Tor browser"},
  {Port = 9191, Description = "Sierra Wireless Airlink"},
  {Port = 9199, Description = "Avtex LLC—qStats"},
  {Port = 9200, Description = "Elasticsearch—default Elasticsearch port"},
  {Port = 9217, Description = "iPass Platform Service"},
  {Port = 9229, Description = "NodeJS debugging default port (localhost)"},
  {Port = 9293, Description = "Sony PlayStation RemotePlay"},
  {Port = 9295, Description = "Sony PlayStation Remote Play Session creation communication port"},
  {Port = 9296, Description = "Sony PlayStation Remote Play"},
  {Port = 9297, Description = "Sony PlayStation Remote Play Video stream"},
  {Port = 9300, Description = "IBM Cognos BI"},
  {Port = 9303, Description = "D-Link Shareport Share storage and MFP printers[citation needed]"},
  {Port = 9306, Description = "Sphinx Native API"},
  {Port = 9309, Description = "Sony PlayStation Vita Host Collaboration WiFi Data Transfer"},
  {Port = 9312, Description = "Sphinx SphinxQL"},
  {Port = 9332, Description = "Litecoin JSON-RPC server"},
  {Port = 9333, Description = "Litecoin"},
  {Port = 9339, Description = "Used by all Supercell games such as Brawl Stars and Clash of Clans, mobile freemium strategy video games"},
  {Port = 9389, Description = "adws, Microsoft AD DS Web Services, Powershell uses this port"},
  {Port = 9392, Description = "OpenVAS Greenbone Security Assistant web interface"},
  {Port = 9418, Description = "git, Git pack transfer service"},
  {Port = 9419, Description = "MooseFS distributed file system – master control port"},
  {Port = 9420, Description = "MooseFS distributed file system – master command port"},
  {Port = 9421, Description = "MooseFS distributed file system – master client port"},
  {Port = 9422, Description = "MooseFS distributed file system – Chunkservers"},
  {Port = 9425, Description = "MooseFS distributed file system – CGI server"},
  {Port = 9443, Description = "VMware Websense Triton console (HTTPS port used for accessing and administrating a vCenter Server via the Web Management Interface)"},
  {Port = 9535, Description = "mngsuite, LANDesk Management Suite Remote Control"},
  {Port = 9536, Description = "laes-bf, IP Fabrics Surveillance buffering function"},
  {Port = 9600, Description = "Factory Interface Network Service (FINS), a network protocol used by Omron programmable logic controllers[citation needed]"},
  {Port = 9669, Description = "VGG Image Search Engine VISE"},
  {Port = 9675, Description = "Spiceworks Desktop, IT Helpdesk Software"},
  {Port = 9676, Description = "Spiceworks Desktop, IT Helpdesk Software"},
  {Port = 9695, Description = "Content centric networking (CCN, CCNx)[citation needed]"},
  {Port = 9735, Description = "Bitcoin Lightning Network"},
  {Port = 9785, Description = "Viber"},
  {Port = 9800, Description = "WebDAV Source"},
  {Port = 9875, Description = "Club Penguin Disney online game for kids"},
  {Port = 9876, Description = "V Rising Dedicated server"},
  {Port = 9877, Description = "V Rising Dedicated server"},
  {Port = 9898, Description = "Tripwire—File Integrity Monitoring Software"},
  {Port = 9899, Description = "SCTP tunneling (port number used in SCTP packets encapsulated in UDP, RFC 6951)"},
  {Port = 9901, Description = "Banana for Apache Solr"},
  {Port = 9981, Description = "Tvheadend HTTP server (web interface)"},
  {Port = 9982, Description = "Tvheadend HTSP server (Streaming protocol)"},
  {Port = 9987, Description = "TeamSpeak 3 server default (voice) port (for the conflicting service see the IANA list)"},
  {Port = 9993, Description = "ZeroTier Default port for ZeroTier"},
  {Port = 9997, Description = "Splunk port for communication between the forwarders and indexers"},
  {Port = 9999, Description = "Urchin Web Analytics[citation needed]"},
  {Port = 10000, Description = "Network Data Management Protocol (NDMP) Control stream for network backup and restore."},
  {Port = 10001, Description = "Ubiquiti UniFi access points broadcast to 255.255.255.255:10001 (UDP) to locate the controller(s)"},
  {Port = 10009, Description = "Crossfire, a multiplayer online First Person Shooter[citation needed]"},
  {Port = 10011, Description = "TeamSpeak 3 ServerQuery"},
  {Port = 10022, Description = "TeamSpeak 3 ServerQuery over SSH"},
  {Port = 10024, Description = "Zimbra smtp [mta]—to amavis from postfix[citation needed]"},
  {Port = 10025, Description = "Zimbra smtp [mta]—back to postfix from amavis[citation needed]"},
  {Port = 10042, Description = "Mathoid server "},
  {Port = 10050, Description = "Zabbix agent"},
  {Port = 10051, Description = "Zabbix trapper"},
  {Port = 10110, Description = "NMEA 0183 Navigational Data. Transport of NMEA 0183 sentences over TCP or UDP"},
  {Port = 10172, Description = "Intuit Quickbooks client"},
  {Port = 10200, Description = "FRISK Software International's fpscand virus scanning daemon for Unix platforms"},
  {Port = 10212, Description = "GE Intelligent Platforms Proficy HMI/SCADA – CIMPLICITY WebView"},
  {Port = 10308, Description = "Digital Combat Simulator Dedicated Server "},
  {Port = 10346, Description = "TEKWorx Limited – interfaceIT board protocol"},
  {Port = 10468, Description = "Flyer – discovery protocol[citation needed]"},
  {Port = 10480, Description = "SWAT 4 Dedicated Server[citation needed]"},
  {Port = 10505, Description = "BlueStacks (android simulator) broadcast"},
  {Port = 10514, Description = "TLS-enabled Rsyslog (default by convention)"},
  {Port = 10578, Description = "Skyrim Together multiplayer server for The Elder Scrolls V: Skyrim mod."},
  {Port = 10800, Description = "Touhou versus games (Immaterial and Missing Power, Phantasmagoria of Flower View, Scarlet Weather Rhapsody, Hisoutensoku, Hopeless Masquerade and Urban Legend in Limbo)"},
  {Port = 10801, Description = "Bag With Friends multiplayer server for the Peaks of Yore mod."},
  {Port = 10823, Description = "Farming Simulator 2011[citation needed]"},
  {Port = 10891, Description = "Jungle Disk (this port is opened by the Jungle Disk Monitor service on the localhost)[citation needed]"},
  {Port = 10933, Description = "Octopus Deploy Tentacle deployment agent"},
  {Port = 11100, Description = "Risk of Rain multiplayer server"},
  {Port = 11111, Description = "RiCcI, Remote Configuration Interface (Redhat Linux)"},
  {Port = 11112, Description = "ACR/NEMA Digital Imaging and Communications in Medicine (DICOM)"},
  {Port = 11211, Description = "memcached"},
  {Port = 11214, Description = "memcached incoming SSL proxy"},
  {Port = 11215, Description = "memcached internal outgoing SSL proxy"},
  {Port = 11311, Description = "Robot Operating System master"},
  {Port = 11371, Description = "OpenPGP HTTP key server"},
  {Port = 11434, Description = "Ollama to run LLM locally"},
  {Port = 11753, Description = "OpenRCT2 multiplayer"},
  {Port = 12000, Description = "CubeForm, Multiplayer SandBox Game"},
  {Port = 12012, Description = "Audition Online Dance Battle, Korea Server—Status/Version Check"},
  {Port = 12013, Description = "Audition Online Dance Battle, Korea Server"},
  {Port = 12035, Description = "Second Life, used for server UDP in-bound"},
  {Port = 12043, Description = "Second Life, used for LSL HTTPS in-bound"},
  {Port = 12046, Description = "Second Life, used for LSL HTTP in-bound"},
  {Port = 12201, Description = "Graylog Extended Log Format (GELF)[importance?]"},
  {Port = 12222, Description = "Light Weight Access Point Protocol (LWAPP) LWAPP data (RFC 5412)"},
  {Port = 12223, Description = "Light Weight Access Point Protocol (LWAPP) LWAPP control (RFC 5412)"},
  {Port = 12307, Description = "Makerbot UDP Broadcast (client to printer) (JSON-RPC)"},
  {Port = 12308, Description = "Makerbot UDP Broadcast (printer to client) (JSON-RPC)"},
  {Port = 12345, Description = "Cube World"},
  {Port = 12443, Description = "IBM HMC web browser management access over HTTPS instead of default port 443"},
  {Port = 12489, Description = "NSClient/NSClient++/NC_Net (Nagios)"},
  {Port = 12975, Description = "LogMeIn Hamachi (VPN tunnel software; also port 32976)—used to connect to Mediation Server (bibi.hamachi.cc); will attempt to use SSL (TCP port 443) if both 12975 & 32976 fail to connect"},
  {Port = 13008, Description = "Crossfire, a multiplayer online First Person Shooter[citation needed]"},
  {Port = 13075, Description = "Default for BMC Software Control-M/Enterprise Manager Corba communication, though often changed during installation"},
  {Port = 13400, Description = "ISO 13400 Road vehicles — Diagnostic communication over Internet Protocol (DoIP)"},
  {Port = 13720, Description = "Symantec NetBackup—bprd (formerly VERITAS)"},
  {Port = 13721, Description = "Symantec NetBackup—bpdbm (formerly VERITAS)"},
  {Port = 13724, Description = "Symantec Network Utility—vnetd (formerly VERITAS)"},
  {Port = 13782, Description = "Symantec NetBackup—bpcd (formerly VERITAS)"},
  {Port = 13783, Description = "Symantec VOPIED protocol (formerly VERITAS)"},
  {Port = 13785, Description = "Symantec NetBackup Database—nbdb (formerly VERITAS)"},
  {Port = 13786, Description = "Symantec nomdb (formerly VERITAS)"},
  {Port = 14550, Description = "MAVLink Ground Station Port"},
  {Port = 14567, Description = "Battlefield 1942 and mods"},
  {Port = 14652, Description = "Repgen DoxBox reporting tool"},
  {Port = 14800, Description = "Age of Wonders III p2p port"},
  {Port = 15000, Description = "psyBNC"},
  {Port = 15009, Description = "Teltonika networks remote management system (RMS)"},
  {Port = 15010, Description = "Teltonika networks remote management system (RMS)"},
  {Port = 15441, Description = "ZeroNet fileserver[citation needed]"},
  {Port = 15567, Description = "Battlefield Vietnam and mods"},
  {Port = 15345, Description = "XPilot Contact"},
  {Port = 15672, Description = "RabbitMQ management plugin"},
  {Port = 16000, Description = "Oracle WebCenter Content: Imaging (formerly known as Oracle Universal Content Management). Port though often changed during installation"},
  {Port = 16080, Description = "macOS Server Web (HTTP) service with performance cache"},
  {Port = 16200, Description = "Oracle WebCenter Content: Content Server (formerly known as Oracle Universal Content Management). Port though often changed during installation"},
  {Port = 16225, Description = "Oracle WebCenter Content: Content Server Web UI. Port though often changed during installation"},
  {Port = 16250, Description = "Oracle WebCenter Content: Inbound Refinery (formerly known as Oracle Universal Content Management). Port though often changed during installation"},
  {Port = 16261, Description = "Project Zomboid multiplayer. Additional sequential ports used for each player connecting to server.[citation needed]"},
  {Port = 16300, Description = "Oracle WebCenter Content: Records Management (formerly known as Oracle Universal Records Management). Port though often changed during installation"},
  {Port = 16379, Description = "Redis Cluster bus"},
  {Port = 16384, Description = "CISCO Default RTP MIN"},
  {Port = 16400, Description = "Oracle WebCenter Content: Capture (formerly known as Oracle Document Capture). Port though often changed during installation"},
  {Port = 16567, Description = "Battlefield 2 and mods"},
  {Port = 17000, Description = "M17 – Digital RF voice and data protocol with Internet (UDP) gateways (reflectors)."},
  {Port = 17011, Description = "Worms multiplayer"},
  {Port = 17224, Description = "Train Realtime Data Protocol (TRDP) Process Data, network protocol used in train communication."},
  {Port = 17225, Description = "Train Realtime Data Protocol (TRDP) Message Data, network protocol used in train communication."},
  {Port = 17333, Description = "CS Server (CSMS), default binary protocol port"},
  {Port = 17472, Description = "Tanium Communication Port"},
  {Port = 17474, Description = "DMXControl 3 Network Discovery"},
  {Port = 17475, Description = "DMXControl 3 Network Broker"},
  {Port = 17476, Description = "DMXControl 3 Network Broker TLS"},
  {Port = 17500, Description = "Dropbox LanSync Protocol (db-lsp); used to synchronize file catalogs between Dropbox clients on a local network."},
  {Port = 18080, Description = "Monero P2P network communications[citation needed]"},
  {Port = 18081, Description = "Monero incoming RPC calls[citation needed]"},
  {Port = 18091, Description = "memcached Internal REST HTTPS for SSL"},
  {Port = 18092, Description = "memcached Internal CAPI HTTPS for SSL"},
  {Port = 18104, Description = "RAD PDF Service"},
  {Port = 18200, Description = "Audition Online Dance Battle, AsiaSoft Thailand Server status/version check"},
  {Port = 18201, Description = "Audition Online Dance Battle, AsiaSoft Thailand Server"},
  {Port = 18206, Description = "Audition Online Dance Battle, AsiaSoft Thailand Server FAM database"},
  {Port = 18300, Description = "Audition Online Dance Battle, AsiaSoft SEA Server status/version check"},
  {Port = 18301, Description = "Audition Online Dance Battle, AsiaSoft SEA Server"},
  {Port = 18306, Description = "Audition Online Dance Battle, AsiaSoft SEA Server FAM database"},
  {Port = 18333, Description = "Bitcoin testnet[citation needed]"},
  {Port = 18400, Description = "Audition Online Dance Battle, KAIZEN Brazil Server status/version check"},
  {Port = 18401, Description = "Audition Online Dance Battle, KAIZEN Brazil Server"},
  {Port = 18505, Description = "Audition Online Dance Battle R4p3 Server, Nexon Server status/version check"},
  {Port = 18506, Description = "Audition Online Dance Battle, Nexon Server"},
  {Port = 18605, Description = "X-BEAT status/version check"},
  {Port = 18606, Description = "X-BEAT"},
  {Port = 18676, Description = "YouView"},
  {Port = 18769, Description = "iQue Protocol"},
  {Port = 19000, Description = "Audition Online Dance Battle, G10/alaplaya Server status/version check"},
  {Port = 19001, Description = "Audition Online Dance Battle, G10/alaplaya Server"},
  {Port = 19132, Description = "Minecraft: Bedrock Edition multiplayer server"},
  {Port = 19133, Description = "Minecraft: Bedrock Edition IPv6 multiplayer server"},
  {Port = 19150, Description = "Gkrellm Server"},
  {Port = 19226, Description = "Panda Software AdminSecure Communication Agent"},
  {Port = 19294, Description = "Google Talk Voice and Video connections"},
  {Port = 19295, Description = "Google Talk Voice and Video connections"},
  {Port = 19302, Description = "Google Talk Voice and Video connections"},
  {Port = 19531, Description = "systemd-journal-gatewayd"},
  {Port = 19532, Description = "systemd-journal-remote"},
  {Port = 19788, Description = "Mesh Link Establishment protocol for IEEE 802.15.4 radio mesh networks"},
  {Port = 19771, Description = "Softros LAN Messenger uses TCP and UDP ports for collecting user lists and sending messages"},
  {Port = 19812, Description = "4D database SQL Communication"},
  {Port = 19813, Description = "4D database Client Server Communication"},
  {Port = 19814, Description = "4D database DB4D Communication"},
  {Port = 19880, Description = "Softros LAN Messenger uses TCP port for file transfers"},
  {Port = 19999, Description = "Distributed Network Protocol—Secure (DNP—Secure), a secure version of the protocol used in SCADA systems between communicating RTU's and IED's"},
  {Port = 20000, Description = "Distributed Network Protocol (DNP), a protocol used in SCADA systems between communicating RTU's and IED's"},
  {Port = 20560, Description = "Killing Floor"},
  {Port = 20580, Description = "Walljam device communications"},
  {Port = 20581, Description = "Walljam device communications"},
  {Port = 20595, Description = "0 A.D. Empires Ascendant"},
  {Port = 20808, Description = "Ableton Link"},
  {Port = 21025, Description = "Starbound Server (default), Starbound"},
  {Port = 21064, Description = "Default Ingres DBMS server"},
  {Port = 22000, Description = "Syncthing (default)"},
  {Port = 22136, Description = "FLIR Systems Camera Resource Protocol"},
  {Port = 22222, Description = "Davis Instruments, WeatherLink IP"},
  {Port = 22347, Description = "WibuKey, WIBU-SYSTEMS AG Copy protection"},
  {Port = 22350, Description = "CodeMeter, WIBU-SYSTEMS AG Copy protection"},
  {Port = 22351, Description = "CodeMeter-CmWAN, WIBU-SYSTEMS AG Copy protection"},
  {Port = 23073, Description = "Soldat Dedicated Server"},
  {Port = 23399, Description = "Skype default protocol"},
  {Port = 23513, Description = "Duke Nukem 3D source ports"},
  {Port = 24441, Description = "Pyzor spam detection network"},
  {Port = 24444, Description = "NetBeans integrated development environment"},
  {Port = 24465, Description = "Tonido Directory Server for Tonido which is a Personal Web App and P2P platform"},
  {Port = 24554, Description = "BINKP, Fidonet mail transfers over TCP/IP"},
  {Port = 24800, Description = "Synergy: keyboard/mouse sharing software"},
  {Port = 24842, Description = "StepMania: Online: Dance Dance Revolution Simulator"},
  {Port = 25565, Description = "Minecraft (Java Edition) multiplayer server"},
  {Port = 25575, Description = "Minecraft (Java Edition) multiplayer server RCON"},
  {Port = 25826, Description = "collectd default port"},
  {Port = 26000, Description = "id Software's Quake server"},
  {Port = 26822, Description = "MSI MysticLight"},
  {Port = 27000, Description = "PowerBuilder SySAM license server"},
  {Port = 27015, Description = "GoldSrc, Source engine and Source 2 engine dedicated server port"},
  {Port = 27016, Description = "Magicka and Space Engineers server port"},
  {Port = 27017, Description = "MongoDB daemon process (mongod) and routing service (mongos)"},
  {Port = 27036, Description = "Steam (In-Home Streaming)"},
  {Port = 27100, Description = "Screen Play Games controller"},
  {Port = 27374, Description = "Sub7 default."},
  {Port = 27888, Description = "Kaillera server"},
  {Port = 27950, Description = "OpenArena outgoing"},
  {Port = 28000, Description = "Siemens Digital Industries Software license server"},
  {Port = 28001, Description = "Starsiege: Tribes[citation needed]"},
  {Port = 28015, Description = "Rust (video game)"},
  {Port = 28016, Description = "Rust (video game) RCON"},
  {Port = 28200, Description = "VoxelStorm game server"},
  {Port = 28260, Description = "Palo Alto Networks' Panorama HA-1 backup unencrypted sync port."},
  {Port = 28443, Description = "Palo Alto Networks' Panorama-to-managed devices software updates, PAN-OS 8.0 and later."},
  {Port = 28769, Description = "Palo Alto Networks' Panorama HA unencrypted sync port."},
  {Port = 28770, Description = "Palo Alto Networks' Panorama HA-1 backup sync port."},
  {Port = 28852, Description = "Killing Floor[citation needed]"},
  {Port = 28910, Description = "Nintendo Wi-Fi Connection"},
  {Port = 28960, Description = "Call of Duty; Call of Duty: United Offensive; Call of Duty 2; Call of Duty 4: Modern Warfare[citation needed] Call of Duty: World at War (PC platform)"},
  {Port = 29000, Description = "Siemens Digital Industries Software license server"},
  {Port = 29070, Description = "Jedi Knight: Jedi Academy by Ravensoft[citation needed]"},
  {Port = 29920, Description = "Nintendo Wi-Fi Connection"},
  {Port = 30000, Description = "XLink Kai P2P"},
  {Port = 30003, Description = "Amicon FPSU-IP Remote Administration"},
  {Port = 30004, Description = "Amicon FPSU-IP VPN"},
  {Port = 30033, Description = "TeamSpeak 3 File Transfer"},
  {Port = 30120, Description = "Fivem (Default Port) GTA V multiplayer"},
  {Port = 30564, Description = "Multiplicity: keyboard/mouse/clipboard sharing software[citation needed]"},
  {Port = 30814, Description = "BeamMP: Unofficial BeamNG.drive multiplayer mod. Default server port"},
  {Port = 31337, Description = "Back Orifice and Back Orifice 2000 remote administration tools"},
  {Port = 31416, Description = "BOINC RPC"},
  {Port = 31438, Description = "Rocket U2"},
  {Port = 31457, Description = "TetriNET"},
  {Port = 32137, Description = "Immunet Protect (UDP in version 2.0, TCP since version 3.0)"},
  {Port = 32400, Description = "Plex Media Server"},
  {Port = 32764, Description = "A backdoor found on certain Linksys, Netgear and other wireless DSL modems/combination routers"},
  {Port = 32887, Description = "Ace of Spades, a multiplayer FPS video game[citation needed]"},
  {Port = 32976, Description = "LogMeIn Hamachi, a VPN application; also TCP port 12975 and SSL (TCP 443)."},
  {Port = 33434, Description = "traceroute"},
  {Port = 33848, Description = "Jenkins, a continuous integration (CI) tool"},
  {Port = 34000, Description = "Infestation: Survivor Stories (formerly known as The War Z), a multiplayer zombie video game[verification needed]"},
  {Port = 34197, Description = "Factorio, a multiplayer survival and factory-building game"},
  {Port = 35357, Description = "OpenStack Identity (Keystone) administration[self-published source?]"},
  {Port = 36330, Description = "Folding@home Control Port"},
  {Port = 37008, Description = "TZSP intrusion detection[citation needed]"},
  {Port = 38412, Description = "NG Application Protocol (NGAP) for communication between a gNB and AMF in 5G core networks"},
  {Port = 40000, Description = "SafetyNET p – a real-time Industrial Ethernet protocol"},
  {Port = 41121, Description = "Tentacle Server – Pandora FMS"},
  {Port = 41230, Description = "Z-Wave Protocol over DTLS"},
  {Port = 41794, Description = "Crestron Control Port – Crestron Electronics"},
  {Port = 41795, Description = "Crestron Terminal Port – Crestron Electronics"},
  {Port = 41796, Description = "Crestron Secure Control Port – Crestron Electronics"},
  {Port = 41797, Description = "Crestron Secure Terminal Port – Crestron Electronics"},
  {Port = 42999, Description = "Curiosity "},
  {Port = 43110, Description = "ZeroNet web UI default port "},
  {Port = 44123, Description = "Z-Wave Secure Tunnel"},
  {Port = 44405, Description = "Mu Online Connect Server[citation needed]"},
  {Port = 44818, Description = "EtherNet/IP explicit messaging"},
  {Port = 48556, Description = "drive.web AC/DC Drive Automation and Control Networks "},
  {Port = 48656, Description = "Brainy LAB Control Server"},
  {Port = 48657, Description = "Brainy LAB Control Server"},
  {Port = 49151, Description = "\"IANA Reserved\""},
  {Port = 49160, Description = "Palo Alto Networks' Panorama."},
  {Port = 50160, Description = "S-CONNECT protocol - data exchange (TCP) and manual device pairing (UDP)."},
  {Port = 50161, Description = "S-CONNECT protocol - automatic device pairing."},
  {Port = 51413, Description = "Transmission (BitTorrent client)"},
  {Port = 51515, Description = "Kopia server "},
  {Port = 51820, Description = "WireGuard protocol"},
  {Port = 52380, Description = "Sony VISCA Network Setting Protocol"},
  {Port = 52381, Description = "Sony VISCA over IP Protocol"},
  {Port = 59100, Description = "AudioRelay"},
  {Port = 61616, Description = "ActiveMQ Classic "},
  {Port = 62078, Description = "Apple's lockdownd protocol – used for communicating with iPhones and iPads."},
  {Port = 64738, Description = "Mumble"},
}

local function load_port_data()
  local mapping = {}
  for _, entry in ipairs(port_data) do
    if entry.Port and type(entry.Port) ~= "string" and entry.Description and entry.Description ~= "" then
      mapping[tonumber(entry.Port)] = entry.Description
    end
  end
  return mapping
end

action = function(host, port)
  local result = {}
  local description_map = load_port_data()

  local port_number = port.number
  local state = port.state

  if (state == "open" or state == "open|filtered" or state == "filtered") then
    local description = description_map[port_number]
    if description then
      table.insert(result, string.format(description))
    end
  end

  if #result > 0 then
    return stdnse.format_output(true, result)
  else
    return "No matches found for the detected ports."
  end
end