'\" t
.\"     Title: nmap-update
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 07/19/2016
.\"    Manual: nmap-update Reference Guide
.\"    Source: nmap-update
.\"  Language: English
.\"
.TH "NMAP\-UPDATE" "1" "07/19/2016" "nmap\-update" "nmap\-update Reference Guide"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nmap-update \- Updater for Nmap\*(Aqs architecture\-independent files
.SH "SYNOPSIS"
.HP \w'\fBnmap\-update\fR\ 'u
\fBnmap\-update\fR [\fIoptions\fR] [\fIchannel\fR]
.SH "DESCRIPTION"
.PP
nmap\-update is an updater for Nmap\*(Aqs architecture\-independent files\&. It is used to keep up to date with changes and new scripts for the Nmap Scripting Engine\&.
.PP
Updates are distributed in the form of
\(lqchannels\(rq, which are named directories that usually correspond to Nmap version numbers\&. When nmap\-update is installed, it will pull from the channel corresponding to the version of Nmap it was installed with, until Nmap and nmap\-update are upgraded as a whole\&.
.PP
The program works by updating from a remote Subversion repository\&. To supply authentication credentials, create a configuration file:
.RS 4 /home/\fIuser\fR/\&.nmap/nmap\-config\&.conf on non\-Windows systems, or .RE .RS 4 C:\eUsers\e\fIuser\fR\eAppData\eRoaming\enmap\enmap\-config\&.conf on Windows\&. .RE
The contents of the file should be:
.sp
.if n \{\
.RS 4
.\}
.nf
username = \fIusername\fR
password = \fIpassword\fR
.fi
.if n \{\
.RE
.\}
.sp
Alternatively, you can cache your credentials more securely if you have the
\fBsvn\fR
command\-line program installed\&. Run the command
\fBsvn ls https://svn\&.nmap\&.org/updates\fR, enter your credentials, and agree to cache them when asked\&.
.SH "OPTIONS SUMMARY"
.PP
\fB\-d \fR\fB\fIdirectory\fR\fR
.RS 4
Install to
\fIdirectory\fR\&. Normally installation goes to a suitable place under your home directory:
\&.nmap/updates/\fIchannel\fR
on Unix and
AppData\eRoaming\enmap\eupdates\e\fIchannel\fR
on Windows\&. This option can be used by root to install updates system\-wide\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Show a help message and exit\&.
.RE
.PP
\fB\-r\fR, \fB\-\-repo\fR \fIrepository\fR
.RS 4
Use the given repository and path rather than the default\&. For example,
\fB\-\-repo https://svn\&.example\&.com/updates\fR\&.
.RE
.PP
\fB\-\-username\fR \fIusername\fR
.RS 4
Authenticate with the given username\&.
.RE
.PP
\fB\-\-password\fR \fIpassword\fR
.RS 4
Authenticate with the given password\&.
.RE
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
Be more verbose\&. Show the used channel and repository\&.
.RE
.PP
Any other arguments are taken to be the names of channels to load from\&. The channels are tried in order until one is successful\&.
