'\" t
.\"     Title: zenmap
.\"    Author: [see the "Authors" section]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 05/17/2023
.\"    Manual: Zenmap Reference Guide
.\"    Source: Zenmap
.\"  Language: English
.\"
.TH "ZENMAP" "1" "05/17/2023" "Zenmap" "Zenmap Reference Guide"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
zenmap \- Graphical Nmap frontend and results viewer
.SH "SYNOPSIS"
.HP \w'\fBzenmap\fR\ 'u
\fBzenmap\fR [\fIoptions\fR] [\fIresults\ file\fR]
.SH "DESCRIPTION"
.PP
Zenmap is a multi\-platform graphical Nmap frontend and results viewer\&. Zenmap aims to make Nmap easy for beginners to use while giving experienced Nmap users advanced features\&. Frequently used scans can be saved as profiles to make them easy to run repeatedly\&. A command creator allows interactive creation of Nmap command lines\&. Scan results can be saved and viewed later\&. Saved scan results can be compared with one another to see how they differ\&. The results of recent scans are stored in a searchable database\&.
.PP
This man page only describes the few Zenmap command\-line options and some critical notes\&. A much more detailed Zenmap User\*(Aqs Guide is available at
\m[blue]\fB\%https://nmap.org/book/zenmap.html\fR\m[]\&. Other documentation and information is available from the Zenmap web page at
\m[blue]\fB\%https://nmap.org/zenmap/\fR\m[]\&.
.SH "OPTIONS SUMMARY"
.PP
\fB\-f\fR, \fB\-\-file \fR\fB\fIresults file\fR\fR
.RS 4
Open the given results file for viewing\&. The results file may be an Nmap XML output file (\&.xml, as produced by
\fBnmap \-oX\fR) or a Umit scan results file (\&.usr)\&. This option may be given more than once\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Show a help message and exit\&.
.RE
.PP
\fB\-n\fR, \fB\-\-nmap \fR\fB\fINmap command line\fR\fR
.RS 4
Run the given Nmap command within the Zenmap interface\&. After
\fB\-n\fR
or
\fB\-\-nmap\fR, every remaining command line argument is read as the command line to execute\&. This means that
\fB\-n\fR
or
\fB\-\-nmap\fR
must be given last, after any other options\&. Note that the command line must include the
\fBnmap\fR
executable name:
\fBzenmap \-n nmap \-sS target\fR\&.
.RE
.PP
\fB\-p\fR, \fB\-\-profile \fR\fB\fIprofile\fR\fR
.RS 4
Start with the given profile selected\&. The profile name is just a string:
"Regular scan"\&. If combined with
\fB\-t\fR, begin a scan with the given profile against the specified target\&.
.RE
.PP
\fB\-t\fR, \fB\-\-target \fR\fB\fItarget\fR\fR
.RS 4
Start with the given target\&. If combined with
\fB\-p\fR, begin a scan with the given profile against the specified target\&.
.RE
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
Increase verbosity (of Zenmap, not Nmap)\&. This option may be given multiple times to get even more verbosity\&.
.RE
.PP
Any other arguments are taken to be the names of results files to open\&.
.SH "ENVIRONMENT VARIABLES"
.PP
\fBZENMAP_DEVELOPMENT\fR
.RS 4
Set
\fBZENMAP_DEVELOPMENT\fR
to disable automatic crash reporting\&.
.RE
.SH "BUGS"
.PP
Like their authors, Nmap and Zenmap aren\(cqt perfect\&. But you can help make them better by sending bug reports or even writing patches\&. If Nmap or Zenmap doesn\(cqt behave the way you expect, first upgrade to the latest version available from
\m[blue]\fB\%https://nmap.org\fR\m[]\&. If the problem persists, do some research to determine whether it has already been discovered and addressed\&. Try Googling the error message or browsing the
nmap\-dev
archives at
\m[blue]\fB\%https://seclists.org/\fR\m[]\&. Read this full manual page as well\&. If nothing comes of this, mail a bug report to
<dev@nmap\&.org>\&. Please include everything you have learned about the problem, as well as what version of Zenmap you are running and what operating system version it is running on\&. Problem reports and Zenmap usage questions sent to dev@nmap\&.org are far more likely to be answered than those sent to Fyodor directly\&.
.PP
Code patches to fix bugs are even better than bug reports\&. Basic instructions for creating patch files with your changes are available at
\m[blue]\fB\%https://svn.nmap.org/nmap/HACKING\fR\m[]\&. Patches may be sent to
nmap\-dev
(recommended) or to Fyodor directly\&.
.SH "HISTORY"
.PP
Zenmap was originally derived from Umit, an Nmap GUI created during the Google\-sponsored Nmap Summer of Code in 2005 and 2006\&. The primary author of Umit was Adriano Monteiro Marques\&. When Umit was modified and integrated into Nmap in 2007, it was renamed Zenmap\&.
.SH "AUTHORS"
.SS "Nmap"
.PP
Fyodor
<fyodor@nmap\&.org>
(\m[blue]\fB\%https://insecure.org\fR\m[])
.PP
Hundreds of people have made valuable contributions to Nmap over the years\&. These are detailed in the
CHANGELOG
file which is distributed with Nmap and also available from
\m[blue]\fB\%https://nmap.org/changelog.html\fR\m[]\&.
.SS "Umit"
.PP
Zenmap is derived from the Umit Nmap frontend, which was started by Adriano Monteiro Marques as an Nmap/Google Summer of Code project (<py\&.adriano@gmail\&.com>,
\m[blue]\fB\%http://www.umitproject.org\fR\m[])\&.
